// 지표별 설명 문구 — 각 국가지표가 무엇을 측정하고 왜 중요한지(가전시장 맥락) 한 줄로.
// v_data_provenance의 indicator 키 기준. 리스트 '설명' 컬럼에서 사용(없으면 단위·출처로 합성 폴백).
export const INDICATOR_DESC: Record<string, string> = {
  account_ownership: "만 15세 이상 인구 중 은행 계좌나 전자지갑 등 금융계좌를 보유한 사람의 비율(%). 세계은행 금융포용지수 기준 금융 접근성을 나타냄.",
  appl_own_cool: "가구 중 에어컨·선풍기 등 냉방기기를 보유한 가구의 비율(%). 인구·보건조사(DHS) 기준 냉방기기 보급 수준을 나타냄.",
  appl_own_mobile: "가구 중 휴대전화를 보유한 가구의 비율(%). 디지털 접근성과 통신 서비스 보급 수준을 나타냄.",
  appl_own_ref: "가구 중 냉장고를 보유한 가구의 비율(%). 인구·보건조사(DHS) 기준 냉장고 보급률로 시장 침투 정도를 나타냄.",
  appl_own_ref_region: "지역별로 집계한 가구 냉장고 보유 비율(%). 지역 간 냉장고 보급 격차를 나타냄.",
  appl_own_tv: "가구 중 TV를 보유한 가구의 비율(%). 인구·보건조사(DHS) 기준 TV 보급 수준을 나타냄.",
  appl_own_tv_region: "지역별로 집계한 가구 TV 보유 비율(%). 지역 간 TV 보급 격차를 나타냄.",
  appl_own_wash: "가구 중 세탁기를 보유한 가구의 비율(%). 인구·보건조사(DHS) 기준 세탁기 보급 수준을 나타냄.",
  appliance_market_cagr: "필리핀 가전시장의 연평균 복합성장률(CAGR, 2025~30 전망치, %). 향후 수년간 시장이 연평균 몇 %씩 성장할지를 나타냄.",
  appliance_market_usd: "필리핀 가전(major appliances) 시장의 연간 매출 규모(달러 기준). 국내에서 판매된 가전제품의 총 시장 가치를 집계한 추정치.",
  bank_loan_growth_yoy: "예금은행 총대출 잔액의 전년동월 대비 증가율(%). 기업·가계에 공급되는 은행 신용이 얼마나 확대·축소되는지를 보여줌.",
  bes_capacity_util: "기업경기조사(BES) 기준 제조업 평균 가동률(%). 조사 대상 제조업체의 생산설비가 실제 가동된 비율을 나타냄.",
  bes_ci_manufacturing: "기업경기조사(BES)의 제조업 부문 신뢰지수(확산지수). 제조업체가 경기를 낙관하는 정도를 낙관−비관 응답 차로 나타냄.",
  bes_ci_next_q: "기업경기조사(BES)의 차분기 경기 전망 확산지수. 기업이 다음 분기 경기를 얼마나 낙관하는지를 나타냄.",
  bes_ci_next12m: "기업경기조사(BES)의 향후 12개월 경기 전망 확산지수. 기업이 1년 뒤 경기를 얼마나 낙관하는지를 나타냄.",
  bes_ci_retail: "기업경기조사(BES)의 도소매업 부문 신뢰지수(확산지수). 유통업체의 경기 심리를 낙관−비관 응답 차로 나타냄.",
  bes_ci_services: "기업경기조사(BES)의 서비스업 부문 신뢰지수(확산지수). 서비스업체의 경기 심리를 낙관−비관 응답 차로 나타냄.",
  bes_con_competition: "기업이 경영 애로로 '경쟁 심화'를 꼽은 응답 비율(%). 시장 경쟁이 얼마나 치열하다고 느끼는지를 나타냄.",
  bes_con_demand: "기업이 경영 애로로 '수요 부족'을 꼽은 응답 비율(%). 판매 부진을 겪는 기업이 얼마나 많은지를 나타냄.",
  bes_con_financial: "기업이 경영 애로로 '재무 문제'를 꼽은 응답 비율(%). 자금난을 겪는 기업의 비중을 나타냄.",
  bes_con_interest: "기업이 경영 애로로 '고금리'를 꼽은 응답 비율(%). 금융비용 부담을 느끼는 기업의 비중을 나타냄.",
  bes_credit_access: "기업경기조사(BES)의 신용 접근 여건 확산지수. 자금 조달이 '수월'하다는 응답에서 '어렵다'는 응답을 뺀 값을 나타냄.",
  bes_employment_outlook: "기업경기조사(BES)의 차분기 고용 전망 확산지수. 다음 분기 채용을 늘리려는 기업이 줄이려는 기업보다 많은 정도를 나타냄.",
  bes_expansion_plans: "설비 확장 계획을 가진 기업의 비율(%). 향후 생산능력을 늘리려는 기업의 투자 의향을 나타냄.",
  bes_financial_condition: "기업경기조사(BES)의 재무여건 확산지수. 기업이 자금 사정을 '양호'하다고 보는 응답에서 '악화'를 뺀 값을 나타냄.",
  bes_overall_ci: "기업경기조사(BES)의 당분기 종합 기업신뢰지수(확산지수). 전 업종 기업의 전반적 경기 심리를 낙관−비관 응답 차로 요약한 값을 나타냄.",
  borrowed_any_pct: "만 15세 이상 인구 중 지난 1년간 어디서든 돈을 빌린 경험이 있는 사람의 비율(%). 가계의 차입 활용도를 나타냄.",
  brent_crude: "북해산 브렌트유 선물의 국제 거래 가격(배럴당 달러). 세계 원유 가격의 대표 기준으로 에너지·물류 비용의 지표가 됨.",
  broad_money_growth: "광의통화(M3) 잔액의 전년 대비 증가율(%). 시중에 풀린 통화량이 얼마나 늘었는지로 유동성 여건을 나타냄.",
  broadband_per100: "인구 100명당 고정 초고속인터넷 가입 건수. 유선 인터넷 인프라의 보급 수준을 나타냄.",
  BSP_odf_rate: "필리핀 중앙은행(BSP) 상시예금창구(ODF)의 금리(%). 정책금리 회랑의 하단을 이루는 금리를 나타냄.",
  BSP_olf_rate: "필리핀 중앙은행(BSP) 상시대출창구(OLF)의 금리(%). 정책금리 회랑의 상단을 이루는 금리를 나타냄.",
  bsp_policy_rate: "필리핀 중앙은행(BSP)의 정책금리(익일물 RRP, %). 통화정책 기조를 대표하는 기준금리를 나타냄.",
  BSP_policy_rate: "필리핀 중앙은행(BSP)의 정책금리인 익일물 역환매약정(RRP) 금리(%). 통화정책 기조를 대표하는 기준금리로, 시중 대출·예금 등 각종 금리의 기준이 됨.",
  business_confidence_index: "BSP 기업기대조사(BES)의 당월 확산지수(CI). 조사 기업 중 경기를 낙관한 비율에서 비관한 비율을 뺀 값으로, 양수면 기업 심리가 순낙관임을 뜻함.",
  business_confidence_next12m: "BSP 기업기대조사(BES) 기준 향후 12개월 경기 전망 확산지수(CI). 기업이 1년 뒤 사업 여건을 얼마나 낙관하는지를 낙관−비관 응답 차로 측정함.",
  capacity_utilization: "제조업 생산설비가 실제로 가동된 비율(평균 가동률, %). 생산능력 대비 실제 생산 수준으로 경기 강도를 나타냄.",
  cdd_monthly: "냉방도일(CDD, 기준온도 24℃). 일평균 기온이 기준온도를 넘은 만큼을 한 달간 합산해 냉방에 필요한 열량 부담을 나타냄.",
  ces_durables_buy: "지난 기간 가전·가구 등 내구재를 실제로 구매한 가구의 비율(%). 내구재 소비가 실제 이뤄진 정도를 나타냄.",
  ces_durables_intent: "소비자기대조사(CES)의 내구재 구매의향 지수(확산지수). 향후 가전·가구 등 내구재를 살 의향을 낙관−비관 응답 차로 나타냄.",
  construction_gfcf_growth: "건설 부문 고정투자(GFCF)의 전년 대비 성장률(%). 건물·구축물에 대한 실물 투자가 얼마나 늘었는지를 나타냄.",
  construction_gva_growth: "건설업 부문 부가가치의 전년 대비 증가율(%). 건물·인프라 건설 활동의 경기 강도를 나타냄.",
  consumer_confidence_index: "필리핀 중앙은행(BSP) 소비자기대조사(CES)의 당분기 확산지수(CI). 약 5천 가구 표본에서 낙관 응답 비율에서 비관 응답 비율을 뺀 값으로, 양수면 소비 심리가 순낙관임을 뜻함.",
  consumer_confidence_next12m: "BSP 소비자기대조사(CES) 기준 향후 12개월 경제 전망의 확산지수(CI). 소비자가 1년 뒤 경기·가계 형편을 얼마나 낙관하는지를 낙관−비관 응답 차로 나타냄.",
  consumer_loan_growth_yoy: "가계 대상 소비자대출 잔액의 전년 대비 증가율(%). 가계 신용이 얼마나 확대·축소되는지를 나타냄.",
  CPI_aircon: "냉·난방기기 부문의 소비자물가지수(CPI, 기준연도=100). 에어컨 등 냉난방 가전의 소매가격 수준을 지수로 나타냄.",
  CPI_all_items: "전 품목을 포괄하는 소비자물가지수(CPI, 2018=100). 가계가 구매하는 상품·서비스 전체의 평균 소매가격 수준을 나타냄.",
  CPI_electricity: "전기요금 부문의 소비자물가지수(CPI, 기준연도=100). 가정용 전기요금의 물가 수준을 지수로 나타냄.",
  CPI_food: "식료품·비주류음료 부문의 소비자물가지수(CPI, 기준연도=100). 먹거리 소매가격 수준을 지수로 나타냄.",
  cpi_forecast_adb: "아시아개발은행(ADB)이 전망한 필리핀 연간 물가상승률(%). 국제기구의 인플레이션 전망치를 나타냄.",
  CPI_household_appliances: "가전제품 부문의 소비자물가지수(CPI, 기준연도=100). 가전 소매가격 수준을 지수로 나타냄.",
  CPI_housing_utilities: "주거·수도·전기·연료 부문의 소비자물가지수(CPI, 기준연도=100). 주거 관련 생활비의 물가 수준을 지수로 나타냄.",
  cpi_inflation_forecast: "필리핀 중앙은행(BSP)이 제시한 연평균 소비자물가 상승률 전망치(%). 중기 인플레이션 목표·기대를 나타냄.",
  cpi_inflation_h1_avg: "상반기(1~6월) 평균 소비자물가 상승률(%). 연중 전반기의 물가 흐름을 요약해 나타냄.",
  cpi_inflation_yoy: "소비자물가지수(CPI)의 전년동월 대비 상승률(%). 가계가 구매하는 상품·서비스 전반의 물가가 1년 전보다 얼마나 올랐는지를 나타냄.",
  CPI_lpg: "취사·난방용 LPG 부문의 소비자물가지수(CPI, 기준연도=100). 가정용 LPG 가격 수준을 지수로 나타냄.",
  CPI_restaurants: "외식·숙박 부문의 소비자물가지수(CPI, 기준연도=100). 음식점·숙박 서비스 가격 수준을 지수로 나타냄.",
  CPI_rice: "주식인 쌀 부문의 소비자물가지수(CPI, 기준연도=100). 쌀 소매가격 수준을 지수로 나타냄.",
  CPI_transport: "교통 부문의 소비자물가지수(CPI, 기준연도=100). 연료·대중교통 등 이동 비용의 물가 수준을 지수로 나타냄.",
  credit_card_loan_growth_yoy: "신용카드 대출 잔액의 전년 대비 증가율(%). 카드를 통한 가계 신용 사용이 얼마나 늘었는지를 나타냄.",
  credit_card_ownership: "성인 중 신용카드를 보유한 사람의 비율(%). 카드 결제·할부의 저변을 나타냄.",
  credit_card_used: "성인 중 실제로 신용카드를 사용한 사람의 비율(%). 카드 결제의 실제 활용도를 나타냄.",
  current_account_pct_gdp: "경상수지(무역·서비스·소득·이전 수지 합계)가 GDP에서 차지하는 비율(%). 값이 음수면 대외 거래에서 순유출(적자)임을 뜻함.",
  debit_card_ownership: "성인 중 직불카드를 보유한 사람의 비율(%). 전자결제 접근성을 나타냄.",
  digital_payment_share: "전체 소매 결제 건수 중 디지털(전자·모바일) 결제가 차지하는 비율(%). 현금 대신 전자결제가 얼마나 확산됐는지를 나타냄.",
  domestic_credit_pct_gdp: "민간부문에 공급된 국내 신용이 GDP에서 차지하는 비율(%). 금융이 실물경제를 얼마나 뒷받침하는지(금융심화)를 나타냄.",
  durables_buying_intention: "향후 12개월 내 내구재를 구매할 의향을 나타내는 지수(확산지수). 소비자의 내구재 구매 계획 강도를 나타냄.",
  ecommerce_market_usd: "필리핀 이커머스(전자상거래) 시장의 연간 거래액 규모(달러). 온라인 판매 채널의 크기를 나타냄.",
  ecommerce_weekly_pct: "매주 온라인 쇼핑을 하는 인터넷 사용자의 비율(%). 이커머스 이용 빈도를 나타냄.",
  economic_sentiment_composite: "소비자기대조사(CES)와 기업기대조사(BES)를 결합해 자체 산출한 경제심리 종합지수(실험적). 소비·기업 심리를 통합해 나타냄.",
  elec_access_pct: "전기를 공급받을 수 있는 인구의 비율(%). 전력망 접근성으로 가전 사용의 기본 인프라 수준을 나타냄.",
  elec_consumption_pc: "국민 1인당 연간 전력소비량(kWh). 전체 전력소비를 인구로 나눈 값으로 생활·산업의 전기 사용 강도를 나타냄.",
  electrification_rate: "전기를 공급받는 가구·인구의 비율(%). 국가 전력 보급 수준을 나타냄.",
  electrification_region: "지역별 전기 보급률(%). 지역 간 전력 인프라 격차를 나타냄.",
  emp_agri_pct: "전체 취업자 중 농림어업에 종사하는 사람의 비율(%). 산업별 고용 구조에서 1차 산업의 비중을 나타냄.",
  emp_industry_pct: "전체 취업자 중 광공업·건설 등 2차 산업에 종사하는 사람의 비율(%). 산업 부문 고용 비중을 나타냄.",
  emp_services_pct: "전체 취업자 중 서비스업에 종사하는 사람의 비율(%). 3차 산업 고용 비중을 나타냄.",
  employed_persons: "일정 기간 취업 상태인 사람의 총수(백만 명). 노동력조사(LFS) 기준 실제 일하고 있는 인구 규모를 나타냄.",
  energy_households: "가정 부문의 최종 에너지 소비량(석유환산 천톤, ktoe). 가구가 냉난방·조리·가전 등에 쓴 에너지 총량을 나타냄.",
  energy_services: "서비스 부문의 최종 에너지 소비량(석유환산 천톤, ktoe). 상업·서비스업이 사용한 에너지 총량을 나타냄.",
  energy_total: "국가 전체의 최종 에너지 소비량(석유환산 천톤, ktoe). 산업·수송·가정 등 모든 부문의 에너지 사용 합계를 나타냄.",
  enso_oni: "적도 태평양 해수면 온도 편차로 엘니뇨·라니냐 강도를 나타내는 지수(ONI). 값이 높으면 엘니뇨(고온·가뭄), 낮으면 라니냐 국면임을 나타냄.",
  exports_gdp: "재화·서비스 수출액이 국내총생산(GDP)에서 차지하는 비율(%). 한 나라 경제가 해외 수요에 얼마나 의존하는지를 나타냄.",
  fdi_net_inflow_usd: "외국인직접투자(FDI)의 순유입액(달러). 외국 자본이 국내 기업·사업에 투자한 금액에서 회수·철수분을 뺀 값.",
  fertility_rate: "여성 1명이 가임기간에 낳을 것으로 기대되는 평균 자녀 수(합계출산율). 인구의 자연 증감과 장기 인구구조를 좌우함.",
  gdp_forecast_adb: "아시아개발은행(ADB)이 전망한 필리핀 실질 GDP 성장률(%). 국제기구의 중기 성장 전망치를 나타냄.",
  gdp_forecast_imf: "국제통화기금(IMF)이 전망한 필리핀 실질 GDP 성장률(%). 국제기구의 중기 성장 전망치를 나타냄.",
  GDP_growth: "국내총생산(GDP)의 성장률(%). 한 나라가 생산한 재화·서비스 총량의 증감을 나타내는 경기 사이클의 핵심 지표.",
  gdp_growth_yoy: "물가 영향을 제거한 실질 국내총생산(GDP)의 전년동기 대비 성장률(%). 한 나라가 생산한 재화·서비스의 총량이 1년 전 같은 기간보다 얼마나 늘었는지를 나타냄.",
  gdp_per_capita_ppp: "구매력평가(PPP) 기준으로 환산한 1인당 국내총생산. 각국 물가 차이를 반영해 실질 생활수준을 국제 비교할 수 있게 한 지표.",
  gdp_per_capita_usd: "명목 환율로 환산한 1인당 국내총생산(달러). 국민 한 사람이 생산한 부가가치의 평균 규모를 나타냄.",
  gdp_target_govt: "필리핀 정부가 제시한 연간 실질 GDP 성장 목표치(%). 정부의 경제운용 목표 수준을 나타냄.",
  gdp_total_ppp: "구매력평가(PPP) 기준으로 환산한 국내총생산 총액. 물가 차이를 반영한 경제 규모를 국제 비교용으로 나타냄.",
  gdp_total_usd: "명목 환율로 환산한 국내총생산 총액(달러). 한 나라 경제의 전체 규모를 나타내는 대표 지표.",
  gfcf_growth: "총고정자본형성(설비·건설·지식재산 투자)의 증가율(%). 기업·정부가 미래 생산능력을 위해 실물자산에 투자한 규모의 변화를 나타냄.",
  gini_index: "소득분배의 불평등도를 나타내는 지니계수(0~1). 값이 클수록 소득이 소수에 집중돼 불평등이 심함을 뜻함.",
  gni_per_capita: "국민총소득(GNI)을 전체 인구로 나눈 1인당 GNI(명목, 달러). 해외 순소득까지 포함한 국민 1인당 평균 소득 수준을 나타냄.",
  govt_debt_gdp: "정부 부채 잔액이 국내총생산(GDP)에서 차지하는 비율(%). 국가 재정의 건전성과 부채 부담 정도를 가늠하는 지표.",
  govt_exp_gdp: "정부 지출이 국내총생산(GDP)에서 차지하는 비율(%). 재정을 통한 경기 부양의 강도를 나타냄.",
  grdp_per_capita_region: "지역별 1인당 지역내총생산(GRDP, 불변가격). 지역 간 소득·생산 수준의 격차를 나타냄.",
  grdp_region: "지역별 지역내총생산(GRDP, 불변가격). 각 지역 경제의 생산 규모를 나타냄.",
  gross_capital_formation_yoy: "총자본형성(고정투자+재고증감)의 전년 대비 증가율(%). 경제 전체의 실물 투자가 얼마나 늘었는지를 나타냄.",
  gross_savings_gdp: "국민총저축이 GDP에서 차지하는 비율(%). 소득 중 소비하지 않고 저축된 부분의 규모를 나타냄.",
  hh_consumption_gdp: "가계 최종소비지출이 GDP에서 차지하는 비율(%). 경제에서 민간 소비가 차지하는 비중을 나타냄.",
  hh_consumption_growth: "가계 최종소비지출의 증가율(%). 가계가 재화·서비스 구매에 쓴 지출이 얼마나 늘었는지로 내수 소비의 활력을 보여줌.",
  hh_consumption_pc: "물가를 반영한 불변가격 기준 1인당 가계소비 지출. 국민 한 사람의 평균 실질 소비 수준을 나타냄.",
  household_consumption_yoy: "가계 최종소비지출의 전년 대비 증가율(%). 민간 소비가 얼마나 늘었는지로 내수 강도를 나타냄.",
  household_income_region: "지역별 가구당 평균 연간 소득(페소). 지역 간 가계 소득·구매력 격차를 나타냄.",
  household_size: "한 가구를 구성하는 평균 가구원 수(명). 가구의 평균 규모를 나타냄.",
  households_mn: "전국의 총 가구 수. 가구 단위 수요의 기본 규모를 나타냄.",
  households_region: "지역별 가구 수. 지역별 가구 단위 수요의 규모를 나타냄.",
  imports_consumer_electronics: "소비자용 전자제품의 수입액(CIF 기준, 달러). 완제품 형태로 들여온 소비자 전자기기의 수입 규모를 집계한 값.",
  imports_gdp: "재화·서비스 수입액이 국내총생산(GDP)에서 차지하는 비율(%). 경제의 해외 조달 의존도를 나타냄.",
  imports_home_appliances: "필리핀의 가전제품 수입액(CIF 기준, 달러). 해외에서 들여온 가전제품의 수입 규모를 무역통계로 집계한 값.",
  imports_telecom: "통신기기의 수입액(CIF 기준, 달러). 해외에서 들여온 통신·IT 기기의 수입 규모를 나타냄.",
  industry_gva_yoy: "산업(광공업·건설·전기 등) 부문 총부가가치의 전년 대비 증가율(%). 제조·건설 중심 실물 생산 활동의 경기 강도를 나타냄.",
  industry_va_gdp: "산업(광공업·건설 등) 부가가치가 GDP에서 차지하는 비율(%). 경제의 산업 구조를 나타냄.",
  industry_va_growth: "산업 부문 부가가치의 전년 대비 증가율(%). 광공업·건설 등 실물 생산의 경기 강도를 나타냄.",
  INF_aircon: "냉·난방기기(에어컨 등) 부문 소비자물가지수의 전년동월 대비 상승률(%). 냉난방 가전 소매가격의 변동을 측정함.",
  INF_all_items: "전 품목을 포함한 소비자물가지수(CPI)의 전년동월 대비 상승률(%), 즉 헤드라인 인플레이션. PSA가 가계가 구매하는 고정 상품·서비스 바스켓의 평균 소매가 변동을 기준연도(2018=100) 대비로 측정함.",
  INF_electricity: "전기요금 부문 소비자물가지수의 전년동월 대비 상승률(%). 가정용 전력 요금이 1년 전보다 얼마나 오르거나 내렸는지를 측정함.",
  INF_food: "식료품·비주류음료 부문 소비자물가지수의 전년동월 대비 상승률(%). 가계 필수 지출의 큰 비중을 차지하는 먹거리 물가의 변동을 나타냄.",
  INF_household_appliances: "가전제품 부문 소비자물가지수의 전년동월 대비 상승률(%). 냉장고·세탁기·TV 등 가전 소매가격이 1년 전보다 얼마나 오르거나 내렸는지를 나타냄.",
  INF_housing_utilities: "주거·수도·전기·연료 부문 소비자물가지수의 전년동월 대비 상승률(%). 주거 관련 기초 생활비의 물가 변동을 측정함.",
  INF_lpg: "취사·난방용 LPG(액화석유가스) 부문 소비자물가지수의 전년동월 대비 상승률(%). 가정용 가스 연료 가격의 변동을 나타냄.",
  INF_restaurants: "외식·숙박 부문 소비자물가지수의 전년동월 대비 상승률(%). 음식점·숙박 등 서비스 소비 가격의 변동을 나타냄.",
  INF_rice: "주식인 쌀 부문 소비자물가지수의 전년동월 대비 상승률(%). 필수 식품인 쌀 소매가격의 변동을 측정함.",
  INF_transport: "교통 부문 소비자물가지수의 전년동월 대비 상승률(%). 연료·대중교통 등 이동 관련 비용의 물가 변동을 나타냄.",
  infra_budget_region: "지역별 공공 인프라(DPWH) 예산 규모(페소). 지역 개발·건설 투자의 크기를 나타냄.",
  interbank_call_rate: "은행 간 초단기(익일물) 자금 거래에 적용되는 콜금리의 가중평균(%). 은행들이 하루짜리 자금을 주고받을 때의 시장 단기금리를 나타냄.",
  internet_penetration: "전체 인구 중 인터넷을 이용하는 사람의 비율(%). 디지털·온라인 채널의 저변을 나타냄.",
  labor_force_participation_rate: "15세 이상 생산가능인구 중 취업자와 구직자를 합한 경제활동인구의 비율(%). 노동시장에 참여하는 인구의 크기를 나타냄.",
  life_expectancy: "특정 연도에 태어난 사람이 향후 생존할 것으로 기대되는 평균 수명(년). 국민의 건강·의료 수준을 종합적으로 반영함.",
  m3_growth_yoy: "광의통화(M3) 잔액의 전년동월 대비 증가율(%). 현금·요구불예금에 저축성·정기예금 등을 더한 시중 통화량의 팽창 속도를 나타냄.",
  manuf_va_gdp: "제조업 부가가치가 국내총생산(GDP)에서 차지하는 비율(%). 경제의 제조업 기반을 나타냄.",
  manufacturing_va_growth: "제조업 부문 부가가치의 전년 대비 증가율(%). 공장에서 생산된 재화의 부가가치가 얼마나 늘었는지로 제조 경기를 나타냄.",
  market_cap_gdp: "상장주식 시가총액이 국내총생산(GDP)에서 차지하는 비율(%). 자본시장의 상대적 규모와 발달 정도를 나타냄.",
  median_age: "전체 인구를 나이순으로 나열했을 때 정중앙에 위치하는 사람의 나이(중위연령). 인구의 고령화·젊음 정도를 한눈에 보여줌.",
  meralco_residential_rate: "메트로 마닐라 최대 배전사 Meralco의 가정용 전기 요금 단가(₱/kWh). 가구가 실제 부담하는 소매 전기요금 수준을 매월 나타냄.",
  min_wage_php: "수도권(NCR) 비농업 부문의 일 최저임금(페소/일). 저임금 근로자의 법정 최저 하루 임금을 나타냄.",
  mobile_per100: "인구 100명당 이동전화 가입 건수. 모바일 통신 서비스의 보급·침투 수준을 나타냄.",
  ncr_minimum_wage: "수도권(NCR) 지역임금·생산성위원회가 고시한 비농업 부문 일 최저임금(페소/일). 마닐라 도시권 저임금 근로자의 법정 최저 하루 임금을 나타냄.",
  npl_ratio: "은행 총여신 중 3개월 이상 연체된 부실채권(NPL)의 비율(%). 은행 자산건전성과 신용 리스크 수준을 가늠하는 지표.",
  office_vacancy_ncr: "수도권(메트로 마닐라) 오피스 빌딩의 공실률(%). 임대되지 않고 비어 있는 사무공간의 비율로 상업용 부동산 경기를 나타냄.",
  ofw_cash_remittance: "해외 필리핀 근로자(OFW)가 은행 등 공식 경로를 통해 본국으로 보낸 현금 송금액(달러). BSP가 월별로 집계하는 해외소득 유입의 핵심 지표.",
  ofw_cash_remittance_growth_yoy: "OFW 현금송금액의 전년동월 대비 증가율(%). 해외 근로자 송금 소득이 얼마나 늘거나 줄었는지를 나타냄.",
  ofw_personal_remittance: "OFW 개인송금 총액(현금+현물, 달러). 공식·비공식 경로를 포함한 해외 근로자의 총 송금 규모를 나타냄.",
  ofw_remittance_forecast: "필리핀 중앙은행(BSP)이 제시한 연간 OFW 송금 전망치(달러). 그해 예상되는 송금 소득 규모를 나타냄.",
  ofw_remittance_landbased: "육상 근무 OFW(사무·서비스·건설직 등)가 보낸 송금액(달러). 전체 송금의 대부분을 차지하는 부분을 나타냄.",
  ofw_remittance_seabased: "해상 근무 OFW(선원)가 보낸 송금액(달러). 선박 승선 근로자의 송금 규모를 나타냄.",
  ofw_remittance_total: "OFW가 본국으로 보낸 해외송금의 합계액(달러). BSP가 집계하는 국가 외화소득의 핵심 원천을 나타냄.",
  oil_diesel: "경유(디젤)의 소매 판매가격(₱/리터). 화물·대중교통 등 물류·운송 연료비의 기준이 되는 유종 가격.",
  oil_gasoline: "휘발유의 소매 판매가격(₱/리터). 승용차 등 개인 이동 연료비를 대표하는 유종 가격.",
  oil_kerosene: "등유(케로신)의 소매 판매가격(₱/리터). 취사·난방에 쓰이는 등유 연료의 가격을 나타냄.",
  oil_ron91: "옥탄가 91 휘발유(RON91)의 소매 판매가격(₱/리터). 보급형 휘발유의 가격을 나타냄.",
  oil_ron95: "옥탄가 95 휘발유(RON95)의 소매 판매가격(₱/리터). 고급 휘발유의 가격을 나타냄.",
  permits_nonresidential_floorarea: "정부가 승인한 비주거용(상업·산업) 건축허가의 총 연면적(㎡). 상업·산업 건설 파이프라인을 나타냄.",
  permits_nonresidential_value: "비주거용 건축허가의 총 공사 예정 금액(페소). 상업·산업 건설 투자 규모를 나타냄.",
  permits_residential_floorarea: "정부가 승인한 주거용 건축허가의 총 연면적(㎡). 향후 1~2년 내 준공·입주로 이어질 신규 주택 공급 파이프라인을 나타냄.",
  permits_residential_value: "주거용 건축허가의 총 공사 예정 금액(페소). 주택 건설 투자 규모를 나타냄.",
  permits_total_floorarea: "전체 건축허가의 총 연면적(㎡). 주거·비주거를 합한 건설 착공 파이프라인을 나타냄.",
  permits_total_value: "전체 건축허가의 총 공사 예정 금액(페소). 건설 투자 규모 전반을 나타냄.",
  php_usd_rate: "미국 달러 대비 필리핀 페소 환율(₱/US$, 종가). 1달러를 사는 데 필요한 페소 금액으로, 값이 오르면 페소 약세, 내리면 페소 강세를 뜻함.",
  policy_rate_monthly: "필리핀 중앙은행(BSP) 정책금리(RRP)의 월별 시계열(%). 기준금리 기조의 월간 추이를 나타냄.",
  pop_share_child: "전체 인구 중 0~14세 유소년이 차지하는 비율(%). 장래 인구·노동 공급의 저변을 나타냄.",
  pop_share_old: "전체 인구 중 65세 이상 고령층이 차지하는 비율(%). 인구 고령화의 진행 정도를 나타냄.",
  pop_share_working: "전체 인구 중 생산가능연령(15~64세)이 차지하는 비율(%). 노동·소비의 핵심 연령층 규모를 나타냄.",
  pop_share_youth: "전체 인구 중 20~39세 청년층이 차지하는 비율(%). 신규 가구 형성과 소비의 핵심 연령층 규모를 나타냄.",
  population: "특정 시점에 한 나라에 거주하는 총인구 수. 시장의 기본 규모와 잠재 수요의 크기를 나타냄.",
  population_region: "지역별 인구 수. 각 지역의 시장·수요 규모를 나타냄.",
  poverty_rate: "소득이 최저생계선(빈곤선)에 못 미치는 인구의 비율(%). 국민 중 빈곤 상태에 있는 사람의 규모를 나타냄.",
  poverty_rate_region: "지역별 빈곤율(%). 지역 간 빈곤·구매력 격차를 나타냄.",
  PPI_domestic_appliances: "국내 가전제품 제조업의 생산자물가지수(PPI) 전년 대비 변동률(%). 공장 출고 단계에서 제조업체가 받는 가전 판매가격의 변동을 측정함.",
  PPI_electrical: "전기장비 제조업의 생산자물가지수(PPI) 전년 대비 변동률(%). 전기장비 공장 출고가격의 변동을 나타냄.",
  PPI_electronics: "전자·컴퓨터 제조업의 생산자물가지수(PPI) 전년 대비 변동률(%). 전자제품 공장 출고가격의 변동을 나타냄.",
  PPI_manufacturing: "제조업 전체의 생산자물가지수(PPI) 전년 대비 변동률(%). 공장 출고 단계 전반의 생산원가 흐름을 나타냄.",
  psei_index: "필리핀 증권거래소 대표 주가지수(PSEi, 월말 종가). 시가총액·유동성 상위 30개 대형 상장기업으로 구성된 벤치마크 지수.",
  remittances_usd: "한 해 동안 해외 거주 필리핀인이 본국으로 보낸 개인송금 총액(달러, 연간). 세계은행 기준 수취액으로 국가 외화소득의 큰 축.",
  reserves_usd: "필리핀 중앙은행이 보유한 외환보유액(달러). 대외 결제와 환율 방어에 쓸 수 있는 외화 자산의 총량.",
  residential_property_price_index: "명목 주거용 부동산가격지수(2010=100). 주택 실거래·감정가 기준 자산가치 수준을 장기 시계열로 나타냄.",
  residential_property_price_real_yoy: "물가상승분을 제거한 실질 주거용 부동산가격의 전년동기 대비 상승률(%). 인플레이션을 감안한 실제 주택가치 변동을 나타냄.",
  residential_property_price_yoy: "명목 주거용 부동산가격의 전년동기 대비 상승률(%). 물가를 조정하지 않은 주택가격의 표면적 상승 폭을 나타냄.",
  retail_gva_growth: "소매업 부문 부가가치의 전년 대비 증가율(%). 소매 유통 활동의 부가가치가 얼마나 늘었는지로 소비 경기를 나타냄.",
  retail_sales_bn: "소매판매액 규모. 소비자가 소매점에서 구매한 재화의 총 판매 금액을 나타냄.",
  retail_sales_growth: "소매판매액의 전년 대비 증가율(%). 소매 구매의 증감으로 내수 소비 활력을 나타냄.",
  rppi_index: "필리핀 중앙은행(BSP)이 은행 주택담보대출 실거래 자료를 헤도닉 회귀로 산출하는 전국 주택가격지수(2019=100, 분기). 단독·타운하우스·콘도 등 주택 유형과 수도권(NCR)·지방을 구분해 주거용 부동산 가격 변동을 측정함.",
  rppi_index_condo: "RPPI 하위지수 중 콘도미니엄(공동주택) 유형의 가격지수(2019=100, 분기). BSP가 은행 대출자료를 바탕으로 도심 공동주택의 실거래가 수준 변화를 추정함.",
  rppi_index_house: "RPPI 하위지수 중 단독주택 유형의 가격지수(2019=100, 분기). 단독주택 실거래가 수준의 분기별 변화를 헤도닉 방식으로 측정함.",
  rppi_yoy: "주택가격지수(RPPI)의 전년동기 대비 변동률(%). 전국 주택 실거래가가 1년 전 같은 분기보다 얼마나 오르거나 내렸는지를 나타냄.",
  saved_at_fi_pct: "만 15세 이상 인구 중 지난 1년간 은행 등 공식 금융기관에 저축한 사람의 비율(%). 가계의 금융 저축 기반을 나타냄.",
  secondary_enroll: "중등학교(중·고교) 총취학률(%). 해당 연령대 인구 대비 중등교육 등록 학생 비율로 인적자본 수준을 나타냄.",
  secure_internet_servers: "인구 100만 명당 보안(암호화) 인터넷 서버 수. 전자상거래·디지털 거래를 뒷받침하는 인터넷 인프라 성숙도를 나타냄.",
  services_gva_yoy: "서비스 부문 총부가가치의 전년 대비 증가율(%). 도소매·금융·운수 등 서비스업 생산 활동의 경기 강도를 나타냄.",
  services_pct_gdp: "서비스업 부가가치가 국내총생산(GDP)에서 차지하는 비율(%). 경제의 서비스화 정도와 산업 구조를 나타냄.",
  services_va_gdp: "서비스업 부가가치가 GDP에서 차지하는 비율(%). 경제의 서비스화 정도를 나타냄.",
  services_va_growth: "서비스업 부가가치의 전년 대비 증가율(%). 서비스 부문 생산 활동의 경기 강도를 나타냄.",
  tax_revenue_gdp: "정부 조세수입이 국내총생산(GDP)에서 차지하는 비율(%). 국가의 세금 징수 능력과 재정 기반을 나타냄.",
  temp_monthly: "메트로 마닐라의 월평균 기온(℃). 해당 월의 일평균 기온을 한 달간 평균해 나타냄.",
  tourism_arrivals: "일정 기간 필리핀에 입국한 국제 관광객 수(명). 관광·서비스업 경기와 소비 활력을 가늠하는 지표.",
  trade_balance_gdp: "상품·서비스 수출에서 수입을 뺀 무역수지가 GDP에서 차지하는 비율(%). 값이 음수면 수입이 수출보다 많은 무역적자를 뜻함.",
  underemployment_rate: "취업자 중 추가 취업이나 더 긴 근로시간을 원하는 사람의 비율(%). 겉으로는 취업 상태이나 고용의 질이 낮은 정도를 나타냄.",
  unemployment_rate: "경제활동인구(15세 이상 취업자+구직자) 가운데 일자리 없이 적극적으로 구직 중인 사람의 비율(%). PSA 노동력조사(LFS)로 매월 집계함.",
  urban_pop_pct: "전체 인구 중 도시 지역에 거주하는 인구의 비율(%). 도시화 수준과 도시 소비 밀도를 나타냄.",
  urban_population_pct: "전체 인구 중 도시 지역에 거주하는 인구의 비율(%). 도시화 진행 정도를 나타냄.",
  wholesale_gva_growth: "도매업 부문 부가가치의 전년 대비 증가율(%). 도매 유통 활동의 경기 강도를 나타냄.",
  wholesale_retail_gva_growth: "도매·소매업 전체 부가가치의 전년 대비 증가율(%). 유통 부문의 생산 활동 경기를 종합적으로 나타냄.",
  wholesale_retail_trade_yoy: "도·소매 부가가치의 전년 대비 증가율(%). 유통 부문 전반의 경기를 나타냄.",
}

// 지표별 설명 — 영문(EN 모드). INDICATOR_DESC의 각 키에 대응. 없으면 KO로 폴백(pickL).
export const INDICATOR_DESC_EN: Record<string, string> = {
  account_ownership: "Share of people aged 15+ who hold a financial account such as a bank account or e-wallet (%). Measures financial access under the World Bank financial-inclusion index.",
  appl_own_cool: "Share of households that own cooling appliances such as air conditioners or fans (%). Indicates cooling-appliance penetration per the DHS survey.",
  appl_own_mobile: "Share of households that own a mobile phone (%). Indicates digital access and telecom-service penetration.",
  appl_own_ref: "Share of households that own a refrigerator (%). Refrigerator penetration per the DHS survey, showing market reach.",
  appl_own_ref_region: "Household refrigerator-ownership rate aggregated by region (%). Shows regional gaps in refrigerator penetration.",
  appl_own_tv: "Share of households that own a TV (%). Indicates TV penetration per the DHS survey.",
  appl_own_tv_region: "Household TV-ownership rate aggregated by region (%). Shows regional gaps in TV penetration.",
  appl_own_wash: "Share of households that own a washing machine (%). Indicates washer penetration per the DHS survey.",
  appliance_market_cagr: "Compound annual growth rate of the Philippine appliance market (CAGR, 2025–30 forecast, %). Shows the average yearly growth expected over the coming years.",
  appliance_market_usd: "Annual revenue size of the Philippine major-appliances market (USD). An estimate of the total market value of appliances sold domestically.",
  bank_loan_growth_yoy: "Year-on-year growth in total loans outstanding at deposit banks (%). Shows how bank credit to firms and households is expanding or contracting.",
  bes_capacity_util: "Average manufacturing capacity utilization per the Business Expectations Survey (BES, %). Share of production capacity actually in use among surveyed manufacturers.",
  bes_ci_manufacturing: "Manufacturing-sector confidence index (diffusion index) from the BES. Optimism among manufacturers, as optimist minus pessimist responses.",
  bes_ci_next_q: "Next-quarter business-outlook diffusion index from the BES. How optimistic firms are about the coming quarter.",
  bes_ci_next12m: "Next-12-months business-outlook diffusion index from the BES. How optimistic firms are about conditions a year ahead.",
  bes_ci_retail: "Wholesale & retail confidence index (diffusion index) from the BES. Sentiment among distributors, as optimist minus pessimist responses.",
  bes_ci_services: "Services-sector confidence index (diffusion index) from the BES. Sentiment among service firms, as optimist minus pessimist responses.",
  bes_con_competition: "Share of firms citing 'stronger competition' as a business constraint (%). How intense firms perceive market competition to be.",
  bes_con_demand: "Share of firms citing 'insufficient demand' as a business constraint (%). How many firms face weak sales.",
  bes_con_financial: "Share of firms citing 'financial problems' as a business constraint (%). Share of firms facing funding strain.",
  bes_con_interest: "Share of firms citing 'high interest rates' as a business constraint (%). Share of firms feeling financing-cost pressure.",
  bes_credit_access: "Credit-access diffusion index from the BES. 'Easy'-to-borrow responses minus 'difficult' responses.",
  bes_employment_outlook: "Next-quarter employment-outlook diffusion index from the BES. Extent to which firms plan to hire more rather than fewer next quarter.",
  bes_expansion_plans: "Share of firms with capacity-expansion plans (%). Firms' investment intent to expand future production capacity.",
  bes_financial_condition: "Financial-condition diffusion index from the BES. 'Good'-funding responses minus 'deteriorating' responses.",
  bes_overall_ci: "Current-quarter overall business confidence index (diffusion index) from the BES. Summarizes overall sentiment across sectors as optimist minus pessimist responses.",
  borrowed_any_pct: "Share of people aged 15+ who borrowed money from any source in the past year (%). Indicates household use of credit.",
  brent_crude: "International futures price of North Sea Brent crude (USD per barrel). A benchmark for world oil prices and a gauge of energy and logistics costs.",
  broad_money_growth: "Year-on-year growth of broad money (M3) outstanding (%). Shows liquidity conditions via how much money supply has grown.",
  broadband_per100: "Fixed broadband subscriptions per 100 people. Indicates the penetration of wired internet infrastructure.",
  BSP_odf_rate: "Rate on the BSP's Overnight Deposit Facility (ODF, %). Forms the floor of the policy-rate corridor.",
  BSP_olf_rate: "Rate on the BSP's Overnight Lending Facility (OLF, %). Forms the ceiling of the policy-rate corridor.",
  bsp_policy_rate: "The BSP's policy rate (overnight RRP, %). The benchmark rate representing the monetary-policy stance.",
  BSP_policy_rate: "The BSP's policy rate — the overnight reverse repurchase (RRP) rate (%). The benchmark that represents the monetary-policy stance and anchors market lending and deposit rates.",
  business_confidence_index: "Current-month diffusion index (CI) from the BSP Business Expectations Survey (BES). Optimist share minus pessimist share; a positive value means net-optimistic business sentiment.",
  business_confidence_next12m: "Next-12-months business-outlook diffusion index (CI) from the BSP BES. Measures how optimistic firms are about conditions a year ahead, as optimist minus pessimist responses.",
  capacity_utilization: "Share of manufacturing capacity actually in use (average utilization, %). Actual output relative to capacity, indicating cyclical strength.",
  cdd_monthly: "Cooling degree days (CDD, base 24°C). Sums how far daily mean temperature exceeds the base over a month, indicating cooling-energy demand.",
  ces_durables_buy: "Share of households that actually bought durables such as appliances or furniture in the prior period (%). Shows how much durable-goods consumption occurred.",
  ces_durables_intent: "Durable-goods buying-intention index (diffusion index) from the Consumer Expectations Survey (CES). Intent to buy appliances or furniture, as optimist minus pessimist responses.",
  construction_gfcf_growth: "Year-on-year growth of construction fixed investment (GFCF, %). Shows how much real investment in buildings and structures has grown.",
  construction_gva_growth: "Year-on-year growth of construction-sector value added (%). Indicates cyclical strength of building and infrastructure activity.",
  consumer_confidence_index: "Current-quarter diffusion index (CI) from the BSP Consumer Expectations Survey (CES). Optimist minus pessimist share across a ~5,000-household sample; positive means net-optimistic sentiment.",
  consumer_confidence_next12m: "Next-12-months economic-outlook diffusion index (CI) from the BSP CES. How optimistic consumers are about the economy and household finances a year ahead, as optimist minus pessimist responses.",
  consumer_loan_growth_yoy: "Year-on-year growth in consumer loans outstanding to households (%). Shows how household credit is expanding or contracting.",
  CPI_aircon: "Consumer price index for the heating & cooling appliances group (CPI, base year = 100). Retail price level of ACs and other climate appliances as an index.",
  CPI_all_items: "All-items consumer price index (CPI, 2018 = 100). Average retail price level of all goods and services households buy.",
  CPI_electricity: "Consumer price index for the electricity group (CPI, base year = 100). Price level of residential electricity as an index.",
  CPI_food: "Consumer price index for food & non-alcoholic beverages (CPI, base year = 100). Retail price level of food as an index.",
  cpi_forecast_adb: "Asian Development Bank (ADB) forecast for annual Philippine inflation (%). An international agency's inflation projection.",
  CPI_household_appliances: "Consumer price index for the household-appliances group (CPI, base year = 100). Retail price level of appliances as an index.",
  CPI_housing_utilities: "Consumer price index for housing, water, electricity & fuels (CPI, base year = 100). Price level of housing-related living costs as an index.",
  cpi_inflation_forecast: "The BSP's forecast for average annual consumer inflation (%). Reflects the medium-term inflation target and expectations.",
  cpi_inflation_h1_avg: "Average consumer inflation for the first half (Jan–Jun, %). Summarizes the price trend over the first half of the year.",
  cpi_inflation_yoy: "Year-on-year change in the consumer price index (CPI, %). How much prices of goods and services households buy have risen versus a year earlier.",
  CPI_lpg: "Consumer price index for cooking/heating LPG (CPI, base year = 100). Price level of household LPG as an index.",
  CPI_restaurants: "Consumer price index for restaurants & accommodation (CPI, base year = 100). Price level of dining and lodging services as an index.",
  CPI_rice: "Consumer price index for rice, the staple food (CPI, base year = 100). Retail price level of rice as an index.",
  CPI_transport: "Consumer price index for transport (CPI, base year = 100). Price level of mobility costs such as fuel and public transport as an index.",
  credit_card_loan_growth_yoy: "Year-on-year growth in credit-card loans outstanding (%). Shows how much household credit use via cards has grown.",
  credit_card_ownership: "Share of adults who hold a credit card (%). Indicates the base for card payments and installment purchases.",
  credit_card_used: "Share of adults who actually used a credit card (%). Indicates actual usage of card payments.",
  current_account_pct_gdp: "Current-account balance (trade, services, income and transfers) as a share of GDP (%). A negative value means a net outflow (deficit) in external transactions.",
  debit_card_ownership: "Share of adults who hold a debit card (%). Indicates access to electronic payments.",
  digital_payment_share: "Share of digital (electronic/mobile) payments in total retail payment volume (%). Shows how far electronic payment has spread versus cash.",
  domestic_credit_pct_gdp: "Domestic credit to the private sector as a share of GDP (%). Indicates how much finance supports the real economy (financial deepening).",
  durables_buying_intention: "Index of intention to buy durables in the next 12 months (diffusion index). Strength of consumers' durable-goods purchase plans.",
  ecommerce_market_usd: "Annual transaction size of the Philippine e-commerce market (USD). Indicates the size of the online sales channel.",
  ecommerce_weekly_pct: "Share of internet users who shop online every week (%). Indicates the frequency of e-commerce use.",
  economic_sentiment_composite: "A composite economic-sentiment index combining the CES and BES (experimental, self-computed). Integrates consumer and business sentiment.",
  elec_access_pct: "Share of the population with access to electricity (%). The basic infrastructure level for appliance use.",
  elec_consumption_pc: "Annual electricity consumption per capita (kWh). Total power use divided by population, indicating the intensity of electricity use.",
  electrification_rate: "Share of households/population supplied with electricity (%). Indicates the national level of electricity access.",
  electrification_region: "Electrification rate by region (%). Shows regional gaps in power infrastructure.",
  emp_agri_pct: "Share of the employed working in agriculture, forestry & fishing (%). The weight of the primary sector in the employment structure.",
  emp_industry_pct: "Share of the employed working in industry such as mining, manufacturing and construction (%). The weight of the industrial sector in employment.",
  emp_services_pct: "Share of the employed working in services (%). The weight of the tertiary sector in employment.",
  employed_persons: "Total number of people employed in a given period (millions). The size of the actually-working population per the Labor Force Survey (LFS).",
  energy_households: "Final energy consumption of the household sector (thousand tonnes of oil equivalent, ktoe). Total energy households used for cooling/heating, cooking and appliances.",
  energy_services: "Final energy consumption of the services sector (ktoe). Total energy used by commerce and services.",
  energy_total: "National total final energy consumption (ktoe). The sum of energy use across industry, transport, households and all sectors.",
  enso_oni: "The Oceanic Niño Index (ONI), showing El Niño/La Niña strength from equatorial Pacific sea-surface temperature anomalies. High values indicate El Niño (hot, dry); low values indicate La Niña.",
  exports_gdp: "Exports of goods and services as a share of GDP (%). Indicates how much an economy relies on overseas demand.",
  fdi_net_inflow_usd: "Net inflow of foreign direct investment (FDI, USD). Foreign capital invested in domestic firms and projects, net of withdrawals.",
  fertility_rate: "Average number of children a woman is expected to have over her childbearing years (total fertility rate). Drives natural population change and long-run demographics.",
  gdp_forecast_adb: "Asian Development Bank (ADB) forecast for Philippine real GDP growth (%). An international agency's medium-term growth projection.",
  gdp_forecast_imf: "International Monetary Fund (IMF) forecast for Philippine real GDP growth (%). An international agency's medium-term growth projection.",
  GDP_growth: "Growth rate of gross domestic product (GDP, %). A core business-cycle indicator of change in a nation's total output of goods and services.",
  gdp_growth_yoy: "Year-on-year growth of real GDP, stripping out price effects (%). How much a nation's total output of goods and services grew versus the same period a year earlier.",
  gdp_per_capita_ppp: "GDP per capita converted at purchasing-power parity (PPP). Enables international comparison of real living standards by adjusting for price differences.",
  gdp_per_capita_usd: "GDP per capita converted at market exchange rates (USD). The average value added produced per person.",
  gdp_target_govt: "The Philippine government's annual real GDP growth target (%). Indicates the government's economic-management goal.",
  gdp_total_ppp: "Total GDP converted at purchasing-power parity (PPP). Economy size adjusted for price differences, for international comparison.",
  gdp_total_usd: "Total GDP converted at market exchange rates (USD). The headline measure of an economy's overall size.",
  gfcf_growth: "Growth of gross fixed capital formation (investment in equipment, construction and IP, %). Change in real-asset investment by firms and government for future capacity.",
  gini_index: "The Gini coefficient of income-distribution inequality (0–1). Higher values mean income is more concentrated and inequality is greater.",
  gni_per_capita: "Gross national income (GNI) divided by total population — GNI per capita (nominal, USD). Average income per person including net foreign income.",
  govt_debt_gdp: "Government debt outstanding as a share of GDP (%). A gauge of fiscal soundness and debt burden.",
  govt_exp_gdp: "Government spending as a share of GDP (%). Indicates the strength of fiscal stimulus.",
  grdp_per_capita_region: "Gross regional domestic product per capita by region (GRDP, constant prices). Shows regional gaps in income and output.",
  grdp_region: "Gross regional domestic product by region (GRDP, constant prices). The output size of each regional economy.",
  gross_capital_formation_yoy: "Year-on-year growth of gross capital formation (fixed investment + change in inventories, %). How much economy-wide real investment has grown.",
  gross_savings_gdp: "Gross national savings as a share of GDP (%). The size of income saved rather than consumed.",
  hh_consumption_gdp: "Household final consumption as a share of GDP (%). The weight of private consumption in the economy.",
  hh_consumption_growth: "Growth of household final consumption (%). How much household spending on goods and services grew, showing domestic-demand vitality.",
  hh_consumption_pc: "Household consumption per capita at constant prices. The average real consumption level per person.",
  household_consumption_yoy: "Year-on-year growth of household final consumption (%). Shows domestic-demand strength via how much private consumption grew.",
  household_income_region: "Average annual household income by region (PHP). Shows regional gaps in household income and purchasing power.",
  household_size: "Average number of members per household. Indicates average household size.",
  households_mn: "Total number of households nationwide. The base scale of household-level demand.",
  households_region: "Number of households by region. The scale of household-level demand by region.",
  imports_consumer_electronics: "Imports of consumer electronics (CIF basis, USD). Import size of finished consumer electronic devices.",
  imports_gdp: "Imports of goods and services as a share of GDP (%). Indicates reliance on overseas sourcing.",
  imports_home_appliances: "Philippine imports of home appliances (CIF basis, USD). Import size of appliances brought in from abroad, per trade statistics.",
  imports_telecom: "Imports of telecom equipment (CIF basis, USD). Import size of telecom and IT devices brought in from abroad.",
  industry_gva_yoy: "Year-on-year growth of industry (mining, manufacturing, construction, utilities) gross value added (%). Cyclical strength of manufacturing- and construction-led real output.",
  industry_va_gdp: "Industry (mining, manufacturing, construction) value added as a share of GDP (%). Indicates the industrial structure of the economy.",
  industry_va_growth: "Year-on-year growth of industry-sector value added (%). Cyclical strength of real output such as manufacturing and construction.",
  INF_aircon: "Year-on-year change in the CPI for heating & cooling appliances (ACs, etc.) (%). Measures the change in retail prices of climate appliances.",
  INF_all_items: "Year-on-year change in the all-items CPI (%), i.e. headline inflation. The PSA measures the average change in retail prices of a fixed basket households buy, versus the base year (2018 = 100).",
  INF_electricity: "Year-on-year change in the electricity CPI (%). How much residential electricity tariffs rose or fell versus a year earlier.",
  INF_food: "Year-on-year change in the food & non-alcoholic beverages CPI (%). Change in food prices, a large share of household spending.",
  INF_household_appliances: "Year-on-year change in the household-appliances CPI (%). How much appliance retail prices (fridges, washers, TVs) rose or fell versus a year earlier.",
  INF_housing_utilities: "Year-on-year change in the housing, water, electricity & fuels CPI (%). Measures the change in basic housing-related living costs.",
  INF_lpg: "Year-on-year change in the cooking/heating LPG CPI (%). Change in household gas-fuel prices.",
  INF_restaurants: "Year-on-year change in the restaurants & accommodation CPI (%). Change in prices of dining and lodging services.",
  INF_rice: "Year-on-year change in the rice CPI (%). Measures the change in retail prices of rice, an essential food.",
  INF_transport: "Year-on-year change in the transport CPI (%). Change in mobility-related costs such as fuel and public transport.",
  infra_budget_region: "Public infrastructure (DPWH) budget by region (PHP). Indicates the size of regional development and construction investment.",
  interbank_call_rate: "Weighted-average call rate on overnight interbank lending (%). The short-term market rate at which banks lend each other overnight funds.",
  internet_penetration: "Share of the population that uses the internet (%). Indicates the base for digital and online channels.",
  labor_force_participation_rate: "Share of the working-age population (15+) that is in the labor force — employed plus job-seekers (%). Indicates the size of labor-market participation.",
  life_expectancy: "The average lifespan a person born in a given year is expected to live (years). Reflects overall health and medical standards.",
  m3_growth_yoy: "Year-on-year growth of broad money (M3) outstanding (%). The pace of money-supply expansion, adding savings/time deposits to cash and demand deposits.",
  manuf_va_gdp: "Manufacturing value added as a share of GDP (%). Indicates the manufacturing base of the economy.",
  manufacturing_va_growth: "Year-on-year growth of manufacturing value added (%). Indicates factory-sector conditions via how much value added from factory output grew.",
  market_cap_gdp: "Listed-equity market capitalization as a share of GDP (%). Indicates the relative size and development of the capital market.",
  median_age: "The age of the person in the exact middle when the population is ordered by age (median age). Shows at a glance how young or aging the population is.",
  meralco_residential_rate: "The residential electricity tariff of Meralco, Metro Manila's largest distributor (₱/kWh). The retail electricity rate households actually pay, updated monthly.",
  min_wage_php: "Daily minimum wage in the non-agricultural sector of the capital region (NCR) (PHP/day). The statutory minimum daily wage for low-wage workers.",
  mobile_per100: "Mobile subscriptions per 100 people. Indicates the penetration of mobile telecom services.",
  ncr_minimum_wage: "The non-agricultural daily minimum wage set by the NCR regional wage board (PHP/day). The statutory minimum daily wage for low-wage workers in the Manila metro area.",
  npl_ratio: "Share of non-performing loans (NPLs, overdue 3+ months) in total bank loans (%). A gauge of bank asset quality and credit risk.",
  office_vacancy_ncr: "Office-building vacancy rate in the capital region (Metro Manila) (%). Share of office space left empty, indicating commercial-real-estate conditions.",
  ofw_cash_remittance: "Cash remittances sent home by overseas Filipino workers (OFWs) through formal channels such as banks (USD). A key BSP monthly gauge of overseas-income inflows.",
  ofw_cash_remittance_growth_yoy: "Year-on-year growth of OFW cash remittances (%). How much overseas-worker remittance income has risen or fallen.",
  ofw_personal_remittance: "Total OFW personal remittances (cash + in-kind, USD). The total remittance size from overseas workers including formal and informal channels.",
  ofw_remittance_forecast: "The BSP's forecast for annual OFW remittances (USD). The remittance-income size expected for the year.",
  ofw_remittance_landbased: "Remittances sent by land-based OFWs (office, service, construction, etc.) (USD). The portion that makes up most of total remittances.",
  ofw_remittance_seabased: "Remittances sent by sea-based OFWs (seafarers) (USD). The remittance size from shipboard workers.",
  ofw_remittance_total: "Total overseas remittances sent home by OFWs (USD). A key source of the nation's foreign-currency income, compiled by the BSP.",
  oil_diesel: "Retail selling price of diesel (₱/liter). A benchmark fuel price for freight, public transport and logistics costs.",
  oil_gasoline: "Retail selling price of gasoline (₱/liter). A representative fuel price for personal mobility such as passenger cars.",
  oil_kerosene: "Retail selling price of kerosene (₱/liter). Indicates the price of kerosene fuel used for cooking and heating.",
  oil_ron91: "Retail selling price of RON91 octane gasoline (₱/liter). Indicates the price of entry-grade gasoline.",
  oil_ron95: "Retail selling price of RON95 octane gasoline (₱/liter). Indicates the price of premium gasoline.",
  permits_nonresidential_floorarea: "Total floor area of approved non-residential (commercial/industrial) building permits (㎡). Indicates the commercial and industrial construction pipeline.",
  permits_nonresidential_value: "Total planned construction value of non-residential building permits (PHP). Indicates the size of commercial and industrial construction investment.",
  permits_residential_floorarea: "Total floor area of approved residential building permits (㎡). The new-housing-supply pipeline expected to complete and be occupied within 1–2 years.",
  permits_residential_value: "Total planned construction value of residential building permits (PHP). Indicates the size of housing-construction investment.",
  permits_total_floorarea: "Total floor area of all building permits (㎡). The construction-start pipeline, residential and non-residential combined.",
  permits_total_value: "Total planned construction value of all building permits (PHP). Indicates overall construction-investment size.",
  php_usd_rate: "Philippine peso per US dollar exchange rate (₱/US$, closing). The pesos needed to buy one dollar; a higher value means a weaker peso, lower means stronger.",
  policy_rate_monthly: "Monthly time series of the BSP policy rate (RRP, %). Shows the month-to-month path of the benchmark-rate stance.",
  pop_share_child: "Share of the population aged 0–14 (%). The base of future population and labor supply.",
  pop_share_old: "Share of the population aged 65+ (%). Indicates the degree of population aging.",
  pop_share_working: "Share of the working-age population (15–64) in the total (%). The size of the core age group for labor and consumption.",
  pop_share_youth: "Share of the population aged 20–39 (%). The size of the core age group for new household formation and consumption.",
  population: "Total population residing in a country at a point in time. Indicates the base market size and potential demand.",
  population_region: "Population by region. Indicates the market and demand size of each region.",
  poverty_rate: "Share of people whose income falls below the poverty line (%). The size of the population in poverty.",
  poverty_rate_region: "Poverty rate by region (%). Shows regional gaps in poverty and purchasing power.",
  PPI_domestic_appliances: "Year-on-year change in the producer price index (PPI) for domestic appliance manufacturing (%). Measures the change in factory-gate appliance prices manufacturers receive.",
  PPI_electrical: "Year-on-year change in the PPI for electrical-equipment manufacturing (%). Change in factory-gate prices of electrical equipment.",
  PPI_electronics: "Year-on-year change in the PPI for electronics and computer manufacturing (%). Change in factory-gate prices of electronic products.",
  PPI_manufacturing: "Year-on-year change in the PPI for total manufacturing (%). The trend of factory-gate production costs overall.",
  psei_index: "The Philippine Stock Exchange benchmark index (PSEi, month-end close). A benchmark of the 30 largest listed firms by market cap and liquidity.",
  remittances_usd: "Total personal remittances sent home by overseas Filipinos over a year (USD, annual). Receipts per the World Bank; a major pillar of the nation's foreign-currency income.",
  reserves_usd: "Foreign-exchange reserves held by the BSP (USD). The stock of foreign assets available for external settlement and currency defense.",
  residential_property_price_index: "Nominal residential property price index (2010 = 100). Long time series of housing asset values based on transactions and appraisals.",
  residential_property_price_real_yoy: "Year-on-year change in real residential property prices, stripping out inflation (%). Shows actual housing-value change adjusted for inflation.",
  residential_property_price_yoy: "Year-on-year change in nominal residential property prices (%). The face-value rise in home prices, not adjusted for inflation.",
  retail_gva_growth: "Year-on-year growth of retail-sector value added (%). Indicates consumption conditions via how much retail-distribution value added grew.",
  retail_sales_bn: "Size of retail sales. The total value of goods consumers purchased at retail outlets.",
  retail_sales_growth: "Year-on-year growth of retail sales (%). Indicates domestic consumption vitality via the change in retail purchases.",
  rppi_index: "The BSP's nationwide residential real estate price index, computed from bank mortgage transactions via hedonic regression (2019 = 100, quarterly). Measures price changes by dwelling type (single, townhouse, condo) and area (NCR vs. regions).",
  rppi_index_condo: "The condominium sub-index of the RPPI (2019 = 100, quarterly). The BSP estimates changes in transaction-price levels of urban condominiums from bank loan data.",
  rppi_index_house: "The single-detached-house sub-index of the RPPI (2019 = 100, quarterly). Measures quarterly changes in single-house transaction-price levels via a hedonic method.",
  rppi_yoy: "Year-on-year change in the residential property price index (RPPI, %). How much nationwide home transaction prices rose or fell versus the same quarter a year earlier.",
  saved_at_fi_pct: "Share of people aged 15+ who saved at a formal financial institution in the past year (%). Indicates the household financial-savings base.",
  secondary_enroll: "Gross secondary-school enrollment ratio (%). Enrolled students relative to the corresponding age group, indicating human-capital level.",
  secure_internet_servers: "Secure (encrypted) internet servers per million people. Indicates the maturity of internet infrastructure that supports e-commerce and digital transactions.",
  services_gva_yoy: "Year-on-year growth of services-sector gross value added (%). Cyclical strength of services production such as trade, finance and transport.",
  services_pct_gdp: "Services value added as a share of GDP (%). Indicates the degree of servicization and the industrial structure.",
  services_va_gdp: "Services value added as a share of GDP (%). Indicates the degree of servicization of the economy.",
  services_va_growth: "Year-on-year growth of services value added (%). Cyclical strength of services-sector production.",
  tax_revenue_gdp: "Government tax revenue as a share of GDP (%). Indicates the state's tax-collection capacity and fiscal base.",
  temp_monthly: "Monthly mean temperature in Metro Manila (°C). The daily mean temperature averaged over the month.",
  tourism_arrivals: "Number of international tourist arrivals to the Philippines in a period (persons). A gauge of tourism-and-services conditions and consumption vitality.",
  trade_balance_gdp: "The trade balance (exports minus imports of goods and services) as a share of GDP (%). A negative value means a trade deficit, with imports exceeding exports.",
  underemployment_rate: "Share of the employed who want additional work or longer hours (%). Indicates low employment quality despite nominal employment.",
  unemployment_rate: "Share of the labor force (employed + job-seekers aged 15+) who are without work and actively seeking (%). Compiled monthly by the PSA Labor Force Survey (LFS).",
  urban_pop_pct: "Share of the population living in urban areas (%). Indicates urbanization level and urban consumption density.",
  urban_population_pct: "Share of the population living in urban areas (%). Indicates the degree of urbanization.",
  wholesale_gva_growth: "Year-on-year growth of wholesale-sector value added (%). Cyclical strength of wholesale-distribution activity.",
  wholesale_retail_gva_growth: "Year-on-year growth of combined wholesale & retail value added (%). A comprehensive gauge of production conditions in the distribution sector.",
  wholesale_retail_trade_yoy: "Year-on-year growth of wholesale & retail value added (%). Indicates conditions across the distribution sector.",
}

/**
 * 지표별 LG 인사이트 — 상세 페이지 우측 카드용 3~4문장 해석(So-What 관점, 가전사업 임팩트 중심).
 * 물가(CPI) 우선. 미등록 지표는 카테고리 인사이트(CAT_MI)로 폴백.
 */
export const INDICATOR_INSIGHT: Record<string, string> = {
  cpi_inflation_yoy:
    "헤드라인 물가상승률은 가계 실질 구매력과 BSP 금리 경로를 동시에 좌우하는 핵심 변수다. 물가가 BSP 목표(2~4%) 상단을 넘어서면 금리 인하가 지연돼 할부·소비자금융 비용이 높게 유지되고, 이는 필리핀 가전 수요의 큰 축인 0%할부 판매에 직접적인 제약으로 작용한다. 반대로 물가가 안정 구간에 들어오면 실질소득 회복과 금리 인하 기대가 맞물려 교체·업그레이드 수요가 살아난다. 따라서 물가 둔화 국면에서는 프리미엄·고효율 라인의 판촉 타이밍을, 물가 급등 국면에서는 보급형·에너지절감(TCO) 소구를 강화하는 식으로 라인업·프로모션을 물가 사이클에 맞춰 조정해야 한다.",
  CPI_all_items:
    "전 품목 소비자물가지수는 가계의 전반적 생활비 부담 수준을 보여주며, 필수지출 비중이 높은 필리핀 소비구조상 지수 상승은 가전 같은 재량소비를 먼저 위축시킨다. 지수가 가파르게 오르는 국면에서는 소비자가 구매를 미루거나 저가 모델로 하향 이동하므로, 보급형 라인과 할부 프로모션의 방어력이 중요해진다. 지수가 안정되면 이연됐던 교체 수요가 프리미엄 쪽으로 회복되는 경향이 있다. 물가지수의 방향과 속도를 분기별로 점검해 판촉 강도와 재고 믹스를 선제적으로 조정하는 것이 핵심이다.",
  CPI_household_appliances:
    "가전제품 부문 물가지수는 우리 카테고리의 소매가격이 시장 전체에서 어떻게 움직이는지를 직접 보여주는 지표다. 이 지수가 전체 물가보다 빠르게 오르면 가전 가격 부담이 상대적으로 커져 수요 탄력성이 높은 보급형에서 판매 저항이 커지고, 반대로 완만하면 가격 대비 가치 소구가 유리해진다. 원자재·환율·관세가 이 지수에 시차를 두고 반영되므로, 지수 추세는 향후 소매가 조정과 프로모션 여력을 가늠하는 선행 신호로 활용할 수 있다. 경쟁사 실판가(채널별 가격비교)와 이 지수를 함께 보면 가격 포지셔닝의 타당성을 검증할 수 있다.",
  CPI_electricity:
    "전기요금 물가는 필리핀 소비자가 가전 구매 시 가장 민감하게 반응하는 총소유비용(TCO)의 핵심 축이다. 전기요금이 오를수록 고효율·인버터 모델의 절감 소구가 강력해지므로, 이 지표의 상승 국면은 LG 고효율 라인과 DOE 5성 라벨 마케팅을 전면화할 최적의 타이밍이다. 반대로 전기요금이 안정되면 초기 구매가 민감도가 상대적으로 부각돼 보급형 경쟁이 치열해진다. 에너지 라벨의 월 전기요금(Meralco 연동) 시뮬레이션과 이 지표를 연결해 '고효율=저전기료' 메시지의 설득력을 정량적으로 뒷받침해야 한다.",
  CPI_aircon:
    "냉방기기 부문 물가는 에어컨 소매가 수준을 직접 반영하며, 고온·엘니뇨 국면의 냉방 수요 급증과 맞물려 우리 RAC 사업 수익성에 밀접하다. 이 지수가 오르는 시기는 수요 성수기와 겹치는 경우가 많아 가격 인상 여력이 생기는 반면, 경쟁 심화로 판촉 압력도 커진다. 냉방도일(CDD)·기온 지표와 함께 보면 성수기 진입 시점과 가격·물량 전략을 정교하게 설계할 수 있다. 고효율 인버터의 전기요금 절감 스토리를 성수기 전기요금 상승과 연계하면 프리미엄 소구가 극대화된다.",
  cpi_inflation_forecast:
    "물가 전망치는 향후 BSP 통화정책과 소비심리의 방향을 미리 읽는 선행 지표로, 사업계획·재고·프로모션 캘린더의 전제조건이 된다. 전망이 목표 범위로 하향 안정될 것으로 제시되면 금리 인하와 소비 회복을 전제로 프리미엄·신제품 출시 타이밍을 앞당길 수 있다. 반대로 상방 리스크가 부각되면 보급형 비중 확대와 할부 프로모션 방어를 준비해야 한다. 실측 물가상승률과 전망치의 괴리를 주기적으로 점검해 계획의 유효성을 재검증하는 것이 중요하다.",
  appliance_market_usd:
    "필리핀 가전시장 규모는 우리 사업의 총 기회 크기를 규정하는 최상위 지표다. 시장이 확대되는 국면에서는 신규 보급과 교체 수요가 함께 늘어 프리미엄 라인 확장과 점유율 공격이 유효하고, 정체·축소 국면에서는 점유율 방어와 믹스 개선이 우선순위가 된다. 이 규모를 인구·가구수·보급률과 함께 보면 시장이 침투 확대형인지 교체 중심형인지 판별할 수 있다. LG의 목표 점유율을 절대 매출 목표로 환산하는 기준선으로 활용해야 한다.",
  appliance_market_cagr:
    "가전시장 연평균성장률은 향후 수년간 시장이 얼마나 빠르게 커질지를 나타내며, 중기 투자·라인업·유통 확장 계획의 전제가 된다. 성장률이 높게 유지되면 선제적 라인업 확대와 유통 커버리지 투자가 정당화되고, 둔화되면 수익성 중심의 선택과 집중이 필요하다. 성장의 동력이 신규 보급인지 프리미엄 업그레이드인지에 따라 대응 전략이 달라진다. 경쟁사보다 빠르게 크는 카테고리를 선점하는 것이 점유율 확대의 핵심이다.",
  ecommerce_market_usd:
    "이커머스 시장 규모는 Shopee·Lazada·TikTok 등 온라인 채널의 판매 잠재력을 보여주며, 필리핀 가전 유통의 무게중심이 온라인으로 이동하는 속도를 반영한다. 이 시장이 빠르게 커질수록 D2C·온라인 전용 모델·라이브커머스 투자 우선순위가 높아진다. 온라인 성장은 가격 투명성을 높여 채널 간 가격 정합성 관리가 중요해진다. 오프라인(SM·Abenson) 대비 온라인 비중 추이를 함께 보며 채널 믹스를 조정해야 한다.",
  ofw_remittance_total:
    "OFW 해외송금은 필리핀 가계 구매력의 대들보로, 가전 같은 내구재 소비와 상관이 매우 높다. 송금이 견조하면 교체·업그레이드 수요와 프리미엄 구매 여력이 커지고, 특히 송금 성수기(연말·개학 시즌)에 가전 수요가 집중된다. 페소 약세 국면에서는 달러 송금의 페소 환산액이 늘어 구매력이 추가로 개선되는 효과도 있다. 송금 흐름을 판촉 캘린더·재고 계획과 연동하면 성수기 수요를 선제적으로 잡을 수 있다.",
  ofw_cash_remittance_growth_yoy:
    "송금 증가율은 가계 가처분소득의 단기 모멘텀을 보여주는 선행 신호다. 증가율이 확대되면 몇 개월 시차를 두고 내구재 소비가 살아나는 경향이 있어 가전 수요의 선행지표로 쓸 수 있다. 반대로 둔화·마이너스로 돌아서면 보급형 비중 확대와 할부 프로모션 방어를 준비해야 한다. 송금 모멘텀과 소비자심리를 함께 보면 수요 전환점을 조기에 포착할 수 있다.",
  bsp_policy_rate:
    "BSP 정책금리는 필리핀 가전 판매의 핵심인 할부·소비자금융 비용을 직접 좌우한다. 금리가 높게 유지되면 0%할부 프로모션의 조달 비용이 커지고 소비자 신용 접근성이 낮아져 대형·고가 제품 수요가 억제된다. 금리 인하 사이클이 시작되면 할부 부담 완화와 소비 회복이 맞물려 프리미엄·대형 라인의 판매 여건이 개선된다. 금리 경로를 물가·소비심리와 함께 읽어 프로모션 강도와 라인업 타이밍을 조정해야 한다.",
  policy_rate_monthly:
    "정책금리의 월별 추이는 통화정책 기조의 방향 전환을 조기에 포착하는 데 유용하다. 금리 고점 통과와 인하 전환 시점은 할부금융 비용 하락과 소비 회복의 출발점이므로, 프리미엄·대형 가전 마케팅 확대 타이밍과 직결된다. 반대로 인상 국면에서는 보급형·저가 할부 중심의 방어가 필요하다. 금리 추이를 소비자대출 증가율과 함께 보면 실제 구매력 전환을 확인할 수 있다.",
  unemployment_rate:
    "실업률은 가계 소득 안정성과 소비 심리의 바탕이 되는 지표로, 상승하면 재량소비인 가전 구매가 먼저 위축된다. 고용이 개선(실업률 하락)되면 신규 가구 형성과 소득 기반이 넓어져 보급·교체 수요가 함께 살아난다. 특히 청년·서비스업 고용은 도시 소비층의 가전 수요와 밀접하다. 실업률을 최저임금·송금과 함께 보면 저소득층 구매력의 방향을 종합 판단할 수 있다.",
  gni_per_capita:
    "1인당 국민소득은 소비자의 평균 구매력 수준을 나타내며, 가전 시장이 보급형에서 프리미엄으로 넘어가는 소득 임계선을 가늠하는 데 쓰인다. 소득이 꾸준히 오르면 대형·고효율·프리미엄 라인의 수요 저변이 넓어지고, 정체되면 가성비·할부 중심 경쟁이 심화된다. 지역별 소득 격차와 함께 보면 프리미엄 우선 공략 지역을 식별할 수 있다. 소득 성장 속도는 중장기 라인업 프리미엄화 전략의 근거가 된다.",
  gdp_forecast_adb:
    "성장 전망치는 향후 경기와 소비 여력의 방향을 미리 읽는 지표로, 가전 수요의 중기 사업계획 전제가 된다. 전망이 상향되면 시장 확대를 전제로 라인업·유통 투자를 앞당길 수 있고, 하향되면 수익성 중심의 보수적 운영이 필요하다. 국제기구 전망은 정부 목표치보다 보수적인 경우가 많아, 두 수치의 괴리를 리스크 범위로 활용한다. 성장 전망과 소비·송금 지표를 함께 보며 수요 시나리오를 설계해야 한다.",
  gdp_forecast_imf:
    "IMF 성장 전망은 필리핀 경기의 중기 방향에 대한 국제 벤치마크로, 소비 여력과 가전 수요의 사업계획 전제가 된다. 전망 상향은 시장 확대·투자 확대의 근거가 되고, 하향은 보수적 운영과 수익성 방어의 신호다. ADB·정부 목표치와 나란히 보면 전망의 낙관·비관 폭을 리스크 범위로 활용할 수 있다. 성장 전망을 소비·고용 지표와 연계해 수요 가정을 주기적으로 갱신해야 한다.",
  brent_crude:
    "국제유가는 물류비·제조원가·전반적 물가를 통해 가전 소매가와 소비 여력에 시차를 두고 영향을 준다. 유가 급등은 운송비와 인플레이션을 자극해 실질 구매력을 낮추고 재량소비를 압박하는 반면, 안정되면 물가·금리 완화로 수요 여건이 개선된다. 필리핀은 에너지 수입 의존도가 높아 유가 상승의 소비 위축 효과가 크다. 유가 추세를 물가·국내 유가와 연계해 원가·가격 전략의 선행 신호로 삼아야 한다.",
  oil_ron95:
    "국내 휘발유 소매가는 가계의 이동·물류 비용을 통해 가처분소득과 체감 물가에 직접 작용한다. 유가가 오르면 생활비 부담이 커져 가전 같은 목돈 소비가 뒤로 밀리고, 내리면 소비 여력이 회복된다. 지방·도서 지역일수록 연료비 변동의 소비 영향이 크다. 휘발유가 추세는 단기 소비심리와 방문판매·배송 비용 관리의 참고지표가 된다.",
  elec_consumption_pc:
    "1인당 전력소비는 가전 보급 수준과 생활수준을 반영하는 구조적 지표로, 상승 추세는 냉방·대형가전 보급 확대를 시사한다. 전력소비가 빠르게 느는 지역·소득층은 에어컨·냉장고 등 전력 다소비 가전의 성장 여력이 크다. 동시에 전력소비 증가는 전기요금 부담을 키워 고효율 제품의 TCO 소구를 강화한다. 전력소비를 전기요금·보급률과 함께 보면 고효율 프리미엄 공략 포인트를 잡을 수 있다.",
  cdd_monthly:
    "냉방도일(CDD)은 기온이 냉방 기준을 초과한 정도로, 에어컨 수요를 직접 선행하는 핵심 지표다. CDD가 높은 달·지역일수록 냉방 가전 판매가 급증하므로, 성수기 진입 시점과 재고·프로모션 배치를 이 지표로 조준할 수 있다. 엘니뇨 등 이상고온 국면에서는 CDD가 평년을 크게 웃돌아 RAC 수요가 폭증하는 경향이 있다. CDD 예보를 물량 계획·유통 배분과 연동하면 성수기 기회를 극대화할 수 있다.",
  enso_oni:
    "엘니뇨·라니냐 지수(ONI)는 필리핀 기후의 큰 흐름을 좌우해 냉방 수요와 작황·물가에 영향을 준다. 엘니뇨(고온·건조) 국면에서는 폭염으로 에어컨·냉장고 수요가 급증하는 반면, 라니냐(다우) 국면에서는 태풍·홍수 리스크와 함께 수요 패턴이 달라진다. 이상기후는 성수기 수요의 진폭을 키우므로 사전 물량 확보가 관건이다. ONI 전망을 CDD·태풍 정보와 함께 보며 계절 수요 시나리오를 준비해야 한다.",
  min_wage_php:
    "최저임금은 저소득 근로자의 구매력 하한을 규정해 보급형 가전 수요의 저변을 결정한다. 최저임금 인상은 저소득층의 목돈·할부 구매 여력을 넓혀 엔트리 가전과 소형 제품 수요에 우호적이다. 다만 급격한 인상은 기업 비용을 통해 고용·물가에 부담으로 작용할 수 있어 양면성이 있다. 최저임금 추이를 실업률·물가와 함께 보며 보급형 라인·할부 전략의 타이밍을 잡아야 한다.",
  household_consumption_yoy:
    "가계소비 증가율은 내수 전반의 강도를 보여주는 지표로, 재량소비인 가전 수요와 방향이 대체로 일치한다. 소비가 견조하게 늘면 교체·프리미엄 수요가 함께 살아나고, 둔화되면 필수지출 우선·가전 이연이 나타난다. 소비 모멘텀을 송금·고용·물가와 함께 보면 수요의 지속성을 판단할 수 있다. 회복 초입에서는 프리미엄 마케팅을, 둔화 국면에서는 보급형 방어를 강화하는 것이 유효하다.",
  retail_sales_bn:
    "소매판매액은 소비자가 실제 지출한 규모를 보여주는 실물 소비 지표로, 가전 판매 환경을 가늠하는 직접적 신호다. 소매판매가 확대되는 국면은 유통 트래픽과 구매 전환이 활발하다는 뜻으로 매대·판촉 투자 효율이 높아진다. 반대로 위축되면 재고 조정과 판촉 효율 관리가 우선된다. 소매판매 추세를 이커머스 성장과 함께 보며 온·오프라인 채널 자원 배분을 조정해야 한다.",
  credit_card_ownership:
    "신용카드 보유율은 할부·비대면 결제의 저변을 보여주며, 고가 가전의 분할결제 접근성과 직결된다. 카드 보유가 확대될수록 무이자 할부 프로모션의 도달 범위가 넓어져 대형·프리미엄 판매에 유리하다. 다만 필리핀은 카드 침투율이 낮아 홈크레딧 등 비카드 할부(0%)의 역할이 크다. 카드·비카드 할부 저변을 함께 보며 결제·프로모션 설계를 최적화해야 한다.",
  consumer_loan_growth_yoy:
    "소비자대출 증가율은 가계가 신용을 활용해 소비를 확대하는 정도를 보여주는 수요 모멘텀 지표다. 대출이 빠르게 늘면 할부·목돈 구매 여력이 커져 대형 가전 수요에 우호적이고, 위축되면 신용 기반 구매가 둔화된다. 금리 국면과 함께 보면 신용 사이클의 방향을 읽을 수 있다. 대출 확장 초입은 할부 프로모션을 공격적으로 전개할 적기다.",
  appl_own_ref:
    "냉장고 보유율은 시장 성숙도와 남은 침투 여력을 동시에 보여주는 구조 지표다. 보유율이 낮은 지역·소득층은 신규 보급(첫 구매) 수요가, 이미 높은 지역은 교체·업그레이드(대형·프리미엄) 수요가 중심이 된다. 보유율을 소득·전력보급과 함께 보면 신규 침투형 시장과 교체형 시장을 구분해 공략할 수 있다. 냉장고는 필수 가전이라 보급률 상승 여력이 곧 안정적 성장 기반이다.",
  appl_own_tv:
    "TV 보유율은 시장 성숙도와 교체 수요 잠재력을 보여주며, 높은 보유율은 신규보다 대형화·고화질(OLED·대형 LCD) 교체로 무게중심이 옮겨감을 뜻한다. 도시·고소득층은 프리미엄 대형 TV, 보유율이 낮은 지역은 보급형 첫 구매가 중심이다. 보유율을 소득·전력보급과 함께 보면 프리미엄 업그레이드 여력을 판단할 수 있다. TV는 교체주기가 있어 보급률 정체 구간에서도 대형화 트렌드로 성장 여지가 있다.",
  appl_own_wash:
    "세탁기 보유율은 침투율과 신규 수요 여력을 보여주는 지표로, 낮은 보유율은 큰 미개척 시장을, 높은 보유율은 자동화·대용량 교체 수요를 시사한다. 도시화·소득 상승과 맞물려 수동→전자동, 소형→대형으로 업그레이드가 진행된다. 보유율이 낮은 지역은 보급형 첫 구매, 높은 지역은 프리미엄 교체 공략이 유효하다. 보급률 추이를 가구수·도시화와 함께 보며 침투·교체 전략을 배분해야 한다.",
  bes_overall_ci:
    "기업경기 종합지수는 기업의 투자·고용·구매 심리를 요약해 소비 여력과 B2B·빌트인 수요의 선행 신호로 활용된다. 지수가 개선되면 고용·소득 확대를 통해 소비재 수요에 우호적이고, 호텔·건설·오피스 등 B2B 가전 수요도 함께 늘어난다. 악화되면 투자·채용 위축으로 수요 둔화 리스크가 커진다. 기업심리와 소비자심리를 함께 보면 경기 전환점을 조기에 포착할 수 있다.",
  economic_sentiment_composite:
    "경제심리 종합지수는 소비자·기업 심리를 통합해 내수의 방향성을 요약하는 선행 지표다. 심리가 개선되면 이연됐던 내구재 구매가 살아나며 가전 수요의 반등을 예고하고, 악화되면 재량소비 위축이 먼저 나타난다. 심리 지표는 실물 소비에 선행하는 경향이 있어 프로모션·재고 타이밍 설계에 유용하다. 심리를 송금·소매판매와 함께 보며 수요 시나리오를 조정해야 한다.",
  digital_payment_share:
    "디지털 결제 비중은 이커머스·비대면 판매의 결제 인프라 성숙도를 보여주며, 온라인 가전 구매 전환율과 직결된다. 디지털 결제가 확대될수록 온라인 할부·간편결제 기반의 구매 편의가 높아져 D2C·라이브커머스 매출에 우호적이다. GCash 등 전자지갑 확산은 카드 미보유층의 온라인 구매도 가능케 한다. 디지털 결제 저변을 이커머스 규모와 함께 보며 온라인 채널·결제 전략을 설계해야 한다.",
  population:
    "총인구는 시장의 기본 규모와 잠재 수요의 크기를 규정하는 최상위 구조 지표다. 인구 증가와 젊은 연령구조는 신규 가구 형성과 가전 첫 구매 수요의 장기 성장 기반이 된다. 다만 실제 구매력은 소득·고용과 함께 봐야 하므로, 인구 규모는 수요의 상한을, 소득은 전환 속도를 나타낸다. 지역별 인구분포와 함께 보면 유통·마케팅 자원 배분의 기준이 된다.",
  households_mn:
    "총 가구수는 대당 판매되는 가전 수요의 기본 단위로, 시장 규모를 가장 직접적으로 규정한다. 가구수가 늘수록(핵가족화·도시화 포함) 냉장고·세탁기 등 가구당 1대 가전의 신규 수요가 확대된다. 가구 분화가 빠른 시장은 소형·1인가구용 라인의 기회가 커진다. 가구수를 보급률과 함께 보면 신규+교체 수요의 총량을 추정할 수 있다.",
  permits_total_value:
    "건축허가 금액은 향후 주택·상업시설 착공 파이프라인을 보여주는 선행 지표로, 빌트인·신규 입주 가전 수요를 예고한다. 허가가 늘면 수개월~수년 시차를 두고 신규 주택向 냉장고·에어컨·빌트인 수요가 발생한다. 상업용(호텔·오피스) 허가는 B2B 가전·디스플레이 수요와 연결된다. 건축허가 추세를 건설 경기와 함께 보며 빌트인·B2B 파이프라인을 준비해야 한다.",
  construction_gva_growth:
    "건설업 성장률은 건설 경기의 강도를 보여주며, 신규 주택·상업시설 공급을 통해 빌트인·신규 입주 가전 수요를 선행한다. 건설이 활발하면 수개월 시차로 신규 세대向 가전과 B2B 프로젝트 수요가 늘어난다. 침체되면 신규 수요가 위축돼 교체 수요 중심으로 재편된다. 건설 경기를 건축허가와 함께 보며 빌트인·프로젝트 영업 타이밍을 조율해야 한다.",
  pop_share_youth:
    "청년층 비중은 신규 가구 형성과 소비의 핵심 연령대 규모를 보여주는 구조 지표다. 청년 비중이 높은 시장은 첫 취업·결혼·독립에 따른 가전 첫 구매 수요와 온라인·프리미엄 감수성이 크다. 이 층은 디지털 채널·라이프스타일 소구에 민감해 D2C·SNS 마케팅 효율이 높다. 청년 비중을 도시화·소득과 함께 보며 신규 수요층 공략 전략을 설계해야 한다.",
  urban_population_pct:
    "도시화율은 소비 밀도와 유통 접근성을 좌우해 가전 수요의 집중도를 규정한다. 도시 인구 비중이 높아질수록 대형 유통·전기 인프라·프리미엄 소비가 집중돼 고효율·대형·프리미엄 가전 수요가 커진다. 반대로 지방·도서는 보급형·내구성 중심 수요가 강하다. 도시화 추이를 전력보급·소득과 함께 보며 채널·라인업의 지역 배분을 조정해야 한다.",
}

// 지표별 LG 인사이트 — 영문(EN 모드). INDICATOR_INSIGHT의 각 키에 대응(3~4문장 So-What). 없으면 KO 폴백(pickL).
export const INDICATOR_INSIGHT_EN: Record<string, string> = {
  cpi_inflation_yoy:
    "Headline inflation simultaneously drives household real purchasing power and the BSP's rate path, making it a pivotal variable. When inflation runs above the BSP's 2–4% target, rate cuts are delayed and installment/consumer-finance costs stay high — a direct constraint on the 0%-installment sales that anchor Philippine appliance demand. Conversely, once inflation settles into a stable range, recovering real incomes and rate-cut expectations revive replacement and upgrade demand. Line-up and promotions should therefore be tuned to the inflation cycle: push premium, high-efficiency lines during disinflation, and lean on entry-tier, energy-saving (TCO) messaging during spikes.",
  CPI_all_items:
    "The all-items CPI shows the overall cost-of-living burden, and given the Philippines' high share of essential spending, a rising index squeezes discretionary purchases like appliances first. When the index climbs steeply, consumers defer purchases or trade down to cheaper models, so the resilience of entry lines and installment promos matters most. When it stabilizes, deferred replacement demand tends to recover toward premium. The key is to review the direction and pace of the index quarterly and adjust promo intensity and inventory mix ahead of time.",
  CPI_household_appliances:
    "The appliance-group CPI directly shows how retail prices in our category move relative to the whole market. If it rises faster than overall inflation, the relative price burden grows and sales resistance builds in demand-elastic entry tiers; if it lags, value-for-money messaging becomes advantageous. Since raw materials, FX and tariffs feed into this index with a lag, its trend serves as a leading signal for future retail-price adjustments and promo headroom. Reading it alongside rivals' street prices (Price by Channel) validates our price positioning.",
  CPI_electricity:
    "Electricity inflation is a core pillar of the total cost of ownership (TCO) to which Filipino appliance buyers are most sensitive. The higher electricity prices climb, the more powerful the savings pitch for high-efficiency, inverter models — so an uptrend here is the optimal timing to front-load LG high-efficiency lines and DOE 5-star label marketing. Conversely, when tariffs stabilize, upfront price sensitivity comes to the fore and entry-tier competition intensifies. Linking this indicator to the energy-label monthly-bill (Meralco-tied) simulation quantitatively backs the 'high efficiency = low electric bill' message.",
  CPI_aircon:
    "The cooling-appliance CPI directly reflects AC retail-price levels and, coupled with cooling-demand surges during hot/El Niño phases, is closely tied to our RAC profitability. Periods when this index rises often overlap with peak demand, creating room for price increases — but competitive intensity also raises promo pressure. Read alongside cooling degree days (CDD) and temperature, it lets us precisely design peak-entry timing and price/volume strategy. Tying the inverter electricity-savings story to peak-season tariff increases maximizes the premium pitch.",
  cpi_inflation_forecast:
    "The inflation forecast is a leading read on the direction of BSP policy and consumer sentiment, and a precondition for the business plan, inventory and promo calendar. If the forecast is guided down into the target range, premium and new-product launch timing can be pulled forward on the premise of rate cuts and a consumption recovery. If upside risk builds, prepare to expand the entry-tier share and defend with installment promos. Periodically checking the gap between actual and forecast inflation re-validates the plan.",
  appliance_market_usd:
    "Philippine appliance-market size defines the total opportunity for our business — a top-level metric. In an expanding market, new-adoption and replacement demand rise together, making premium-line expansion and share offense viable; in a flat/shrinking market, share defense and mix improvement take priority. Viewed with population, household count and penetration, it reveals whether the market is penetration-expansion or replacement-led. Use it as the baseline to convert LG's target share into an absolute sales goal.",
  appliance_market_cagr:
    "The appliance-market CAGR shows how fast the market will grow over the coming years and underpins medium-term investment, line-up and distribution-expansion plans. If growth stays high, pre-emptive line-up expansion and coverage investment are justified; if it slows, profitability-focused focus-and-select is needed. The right response differs depending on whether growth is driven by new adoption or premium upgrades. Pre-empting categories growing faster than rivals is central to gaining share.",
  ecommerce_market_usd:
    "E-commerce market size shows the sales potential of online channels like Shopee, Lazada and TikTok, and reflects how fast the center of gravity of Philippine appliance distribution is shifting online. The faster it grows, the higher the priority for D2C, online-exclusive models and live-commerce investment. Online growth raises price transparency, making cross-channel price consistency more important. Track the online-vs-offline (SM, Abenson) share trend to adjust the channel mix.",
  ofw_remittance_total:
    "OFW remittances are the backbone of Philippine household purchasing power and correlate strongly with durable-goods consumption like appliances. When remittances are firm, replacement/upgrade demand and premium affordability grow, with appliance demand concentrating in remittance peak seasons (year-end, back-to-school). During peso weakness, the peso value of dollar remittances rises, further boosting purchasing power. Aligning remittance flows with the promo calendar and inventory plan captures peak-season demand ahead of time.",
  ofw_cash_remittance_growth_yoy:
    "Remittance growth is a leading signal of the short-term momentum of household disposable income. When growth accelerates, durable-goods consumption tends to revive with a lag of a few months, so it works as a leading indicator of appliance demand. If it slows or turns negative, prepare to expand the entry-tier share and defend with installment promos. Reading remittance momentum with consumer sentiment catches demand turning points early.",
  bsp_policy_rate:
    "The BSP policy rate directly drives the installment and consumer-finance costs that are central to Philippine appliance sales. When rates stay high, the funding cost of 0%-installment promos rises and consumer-credit access falls, suppressing demand for large, high-ticket products. Once a cutting cycle begins, easing installment burdens and a consumption recovery improve sales conditions for premium/large lines. Read the rate path with inflation and sentiment to adjust promo intensity and line-up timing.",
  policy_rate_monthly:
    "The monthly path of the policy rate is useful for catching turns in the monetary-policy stance early. The rate peak and the pivot to cuts mark the starting point of falling installment-finance costs and a consumption recovery — directly tied to when to scale up premium/large-appliance marketing. In a hiking phase, defense centered on entry-tier and low-price installments is needed. Reading the rate trend with consumer-loan growth confirms the actual shift in purchasing power.",
  unemployment_rate:
    "Unemployment underpins household income stability and consumer sentiment; when it rises, discretionary appliance purchases contract first. When jobs improve (unemployment falls), new household formation and a broader income base revive both new-adoption and replacement demand. Youth and services-sector employment in particular are closely tied to urban appliance demand. Reading unemployment with the minimum wage and remittances gives a comprehensive view of low-income purchasing power.",
  gni_per_capita:
    "GNI per capita indicates the average purchasing power of consumers and is used to gauge the income threshold at which the market shifts from entry to premium. As income rises steadily, the demand base for large, high-efficiency and premium lines widens; when it stalls, value/installment-centered competition intensifies. Viewed with regional income gaps, it identifies regions to target premium first. The pace of income growth underpins the long-term line-up premiumization strategy.",
  gdp_forecast_adb:
    "The growth forecast reads ahead the direction of the economy and consumption capacity, forming the medium-term business-plan premise for appliance demand. If revised up, line-up and distribution investment can be pulled forward on the premise of market expansion; if down, conservative, profitability-focused operation is needed. International-agency forecasts are often more conservative than government targets, so use the gap between the two as a risk band. Design demand scenarios by reading the growth forecast with consumption and remittance indicators.",
  gdp_forecast_imf:
    "The IMF growth forecast is an international benchmark for the medium-term direction of the Philippine economy and a business-plan premise for consumption capacity and appliance demand. An upward revision supports market and investment expansion; a downward one signals conservative operation and margin defense. Placed alongside ADB and government targets, the spread serves as an optimism/pessimism risk band. Periodically update demand assumptions by linking the forecast to consumption and employment indicators.",
  brent_crude:
    "International oil prices affect appliance retail prices and consumption capacity with a lag, through logistics costs, manufacturing costs and overall inflation. An oil spike fuels transport costs and inflation, lowering real purchasing power and pressuring discretionary spending; when it stabilizes, easing inflation and rates improve demand conditions. The Philippines' high energy-import reliance amplifies the consumption-dampening effect of rising oil. Use the oil trend, linked to inflation and domestic fuel prices, as a leading signal for cost and pricing strategy.",
  oil_ron95:
    "Domestic gasoline retail prices act directly on disposable income and perceived inflation through household mobility and logistics costs. When fuel rises, living-cost burdens grow and big-ticket appliance purchases are pushed back; when it falls, spending capacity recovers. Fuel-price swings hit consumption harder in provincial and island areas. The gasoline-price trend is a reference indicator for short-term sentiment and for managing door-to-door sales and delivery costs.",
  elec_consumption_pc:
    "Per-capita electricity consumption is a structural indicator reflecting appliance penetration and living standards; an uptrend signals expanding adoption of cooling and large appliances. Regions and income tiers where electricity use grows fast have strong growth headroom for power-hungry appliances like ACs and refrigerators. At the same time, rising electricity use enlarges bill burdens, strengthening the TCO pitch for high-efficiency products. Read it with electricity prices and penetration to pinpoint high-efficiency premium targets.",
  cdd_monthly:
    "Cooling degree days (CDD) measure how far temperature exceeds the cooling baseline and directly lead AC demand — a core indicator. In months and regions with high CDD, cooling-appliance sales surge, so use it to target peak-entry timing and inventory/promo placement. In abnormal-heat phases like El Niño, CDD far exceeds the seasonal norm and RAC demand tends to spike. Linking CDD forecasts to volume planning and distribution allocation maximizes peak-season opportunity.",
  enso_oni:
    "The El Niño/La Niña index (ONI) governs the broad flow of Philippine climate, affecting cooling demand, harvests and prices. In an El Niño (hot, dry) phase, heat waves spike AC and refrigerator demand; in a La Niña (wet) phase, demand patterns shift alongside typhoon/flood risk. Abnormal weather amplifies the swing of peak-season demand, so securing volume in advance is key. Prepare seasonal-demand scenarios by reading the ONI outlook with CDD and typhoon information.",
  min_wage_php:
    "The minimum wage sets the floor of purchasing power for low-income workers and thus determines the base of entry-tier appliance demand. Minimum-wage hikes widen low-income households' lump-sum and installment purchasing capacity, favoring entry appliances and small products. However, sharp hikes can burden employment and prices via firm costs, giving them two-sided effects. Read the minimum-wage trend with unemployment and inflation to time entry-line and installment strategy.",
  household_consumption_yoy:
    "Household-consumption growth shows the overall strength of domestic demand and generally moves in the same direction as discretionary appliance demand. When consumption grows firmly, replacement and premium demand revive together; when it slows, essentials-first and appliance deferral appear. Reading consumption momentum with remittances, employment and inflation gauges the durability of demand. Strengthen premium marketing early in a recovery and entry-tier defense during a slowdown.",
  retail_sales_bn:
    "Retail sales show the scale of what consumers actually spend — a real-consumption indicator and a direct signal of the appliance-selling environment. An expanding phase means active distribution traffic and purchase conversion, raising the efficiency of shelf and promo investment. When it contracts, inventory adjustment and promo-efficiency management take priority. Read the retail-sales trend with e-commerce growth to adjust online/offline channel resource allocation.",
  credit_card_ownership:
    "Credit-card ownership shows the base for installment and non-face-to-face payments, directly tied to split-payment access for high-ticket appliances. As card ownership expands, the reach of interest-free installment promos widens, favoring large/premium sales. That said, the Philippines has low card penetration, so non-card installments (0%) via players like Home Credit play a large role. Optimize payment and promo design by reading the card and non-card installment base together.",
  consumer_loan_growth_yoy:
    "Consumer-loan growth shows how much households use credit to expand consumption — a demand-momentum indicator. When loans grow fast, installment and lump-sum purchasing capacity rises, favoring large-appliance demand; when they contract, credit-based buying slows. Read with the rate cycle to gauge the direction of the credit cycle. The early stage of loan expansion is the right time to push installment promos aggressively.",
  appl_own_ref:
    "Refrigerator ownership simultaneously shows market maturity and remaining penetration headroom — a structural indicator. Low-ownership regions and income tiers center on new (first-purchase) demand, while already-high regions center on replacement/upgrade (large, premium) demand. Read ownership with income and electrification to distinguish penetration markets from replacement markets and target each. As an essential appliance, headroom in refrigerator penetration is itself a stable growth base.",
  appl_own_tv:
    "TV ownership shows market maturity and replacement-demand potential; high ownership means the center of gravity shifts from new purchases to larger, higher-resolution (OLED, large LCD) replacements. Urban, high-income tiers center on premium large TVs, while low-ownership regions center on entry-tier first purchases. Read ownership with income and electrification to gauge premium-upgrade headroom. Because TVs have a replacement cycle, there is growth room via the up-sizing trend even where penetration is flat.",
  appl_own_wash:
    "Washer ownership shows penetration and new-demand headroom; low ownership signals a large untapped market, high ownership signals automation and large-capacity replacement demand. Alongside urbanization and rising income, upgrades proceed from manual to fully automatic and small to large. Low-ownership regions favor entry-tier first purchases, high-ownership regions favor premium replacement. Read the penetration trend with household count and urbanization to allocate penetration vs. replacement strategy.",
  bes_overall_ci:
    "The overall business-confidence index summarizes firms' investment, hiring and purchasing sentiment and serves as a leading signal for consumption capacity and B2B/built-in demand. When it improves, expanding employment and income favor consumer-goods demand, and B2B appliance demand from hotels, construction and offices rises too. When it worsens, contracting investment and hiring raise the risk of demand slowdown. Reading business and consumer sentiment together catches cyclical turning points early.",
  economic_sentiment_composite:
    "The composite economic-sentiment index integrates consumer and business sentiment to summarize the direction of domestic demand — a leading indicator. When sentiment improves, deferred durable-goods purchases revive, foreshadowing an appliance-demand rebound; when it worsens, discretionary contraction appears first. Sentiment tends to lead real consumption, making it useful for designing promo and inventory timing. Adjust demand scenarios by reading sentiment with remittances and retail sales.",
  digital_payment_share:
    "The digital-payment share shows the maturity of payment infrastructure for e-commerce and non-face-to-face sales, directly tied to online appliance-purchase conversion. As digital payments expand, online installment and simple-pay convenience rises, favoring D2C and live-commerce revenue. The spread of e-wallets like GCash enables online purchases even by card-less consumers. Design online-channel and payment strategy by reading the digital-payment base with e-commerce size.",
  population:
    "Total population defines the base market size and potential-demand scale — a top-level structural indicator. Population growth and a young age structure form the long-term growth base for new household formation and first-purchase appliance demand. Since actual purchasing power must be read with income and employment, population size represents the ceiling of demand and income the pace of conversion. Read with regional population distribution as the basis for allocating distribution and marketing resources.",
  households_mn:
    "Total household count is the base unit of per-unit appliance demand and most directly defines market size. As households increase (including nuclearization and urbanization), new demand for one-per-household appliances like refrigerators and washers expands. Markets with fast household splitting create bigger opportunities for small/single-person lines. Read household count with penetration to estimate the total of new plus replacement demand.",
  permits_total_value:
    "Building-permit value is a leading indicator of the future housing/commercial construction pipeline, foreshadowing built-in and new-move-in appliance demand. As permits rise, demand for new-home refrigerators, ACs and built-ins arises with a lag of months to years. Commercial (hotel, office) permits connect to B2B appliance and display demand. Read the permit trend with construction activity to prepare the built-in and B2B pipeline.",
  construction_gva_growth:
    "Construction growth shows the strength of building activity and leads built-in and new-move-in appliance demand via new housing/commercial supply. When construction is active, demand for new-unit appliances and B2B projects rises with a lag of several months. When it stalls, new demand contracts and shifts toward replacement demand. Read construction activity with building permits to time built-in and project sales.",
  pop_share_youth:
    "The youth share shows the size of the core age group for new household formation and consumption — a structural indicator. Markets with a high youth share have strong first-purchase appliance demand from first jobs, marriage and independence, plus high online/premium receptivity. This tier is sensitive to digital-channel and lifestyle appeals, giving D2C and social marketing high efficiency. Read the youth share with urbanization and income to design strategy for targeting new demand tiers.",
  urban_population_pct:
    "The urbanization rate governs consumption density and distribution access, defining the concentration of appliance demand. As the urban population share rises, large distribution, electrical infrastructure and premium consumption concentrate, raising demand for high-efficiency, large and premium appliances. Conversely, provincial and island areas have strong entry-tier, durability-centered demand. Read the urbanization trend with electrification and income to adjust regional allocation of channels and line-up.",
}
