// 지표별 설명 문구 — 각 국가지표가 무엇을 측정하고 왜 중요한지(가전시장 맥락) 한 줄로.
// v_data_provenance의 indicator 키 기준. 리스트 '설명' 컬럼에서 사용(없으면 단위·출처로 합성 폴백).
export const INDICATOR_DESC: Record<string, string> = {
  account_ownership: "만 15세 이상 인구 중 은행·전자지갑 등 금융계좌 보유 비율. 할부·카드 결제 기반의 저변을 가늠하는 금융 접근성 지표.",
  appl_own_cool: "가구의 냉방기기·선풍기 보유 비율. 에어컨 신규 수요의 침투 여력을 보여주는 기초 보급 지표.",
  appl_own_mobile: "가구의 휴대폰 보유 비율. 디지털 접근·전자상거래 저변을 나타내는 보급 지표.",
  appl_own_ref: "가구의 냉장고 보유 비율. 냉장고 시장 침투율과 교체·신규 수요 여력을 보여주는 핵심 보급 지표.",
  appl_own_ref_region: "지역별 가구 냉장고 보유 비율. 지역 간 보급 격차로 미개척 수요 지역을 식별.",
  appl_own_tv: "가구의 TV 보유 비율. TV 시장 성숙도와 교체 수요 잠재력을 보여주는 보급 지표.",
  appl_own_tv_region: "지역별 가구 TV 보유 비율. 지역별 보급 격차로 성장 여지를 파악.",
  appl_own_wash: "가구의 세탁기 보유 비율. 세탁기 시장 침투율과 신규 수요 여력을 나타내는 보급 지표.",
  appliance_market_cagr: "필리핀 가전시장의 연평균 성장률(2025~30 전망). 시장 확장 속도를 가늠하는 성장 지표.",
  appliance_market_usd: "필리핀 가전(major appliances) 시장의 연간 매출 규모(달러 기준). 국내에서 판매된 가전제품의 총 시장 가치를 집계한 추정치다.",
  bank_loan_growth_yoy: "예금은행 총대출 잔액의 전년동월 대비 증가율(%). 기업·가계에 공급되는 은행 신용이 얼마나 확대·축소되는지를 보여준다.",
  bes_capacity_util: "기업경기조사(BES) 기준 제조업 평균 가동률. 생산 여력과 경기 강도를 나타냄.",
  bes_ci_manufacturing: "제조업 기업신뢰지수. 제조업 경기 기대를 보여주는 심리 지표.",
  bes_ci_next_q: "차분기 기업경기 전망. 단기 경기 방향성에 대한 기업 심리.",
  bes_ci_next12m: "향후 1년 기업경기 전망. 중기 경기 기대를 나타내는 선행 심리 지표.",
  bes_ci_retail: "도소매업 기업신뢰지수. 유통 경기 심리로 가전 판매 환경을 시사.",
  bes_ci_services: "서비스업 기업신뢰지수. 서비스 경기 심리를 나타냄.",
  bes_con_competition: "기업이 경영 제약으로 꼽은 '경쟁 심화' 응답 비중. 시장 경쟁 강도를 반영.",
  bes_con_demand: "기업 제약 요인 중 '수요 부족' 비중. 내수 위축 신호.",
  bes_con_financial: "기업 제약 요인 중 '재무 문제' 비중. 기업 자금 여건 악화 신호.",
  bes_con_interest: "기업 제약 요인 중 '고금리' 비중. 금융비용 부담을 반영.",
  bes_credit_access: "기업의 신용 접근 여건 지수. 자금 조달 환경을 나타냄.",
  bes_employment_outlook: "차분기 고용 전망 지수. 고용·소득 개선 기대를 반영.",
  bes_expansion_plans: "설비 확장 계획을 가진 기업 비율. 투자 심리와 경기 확장 신호.",
  bes_financial_condition: "기업 재무여건 지수. 기업 자금 사정을 나타냄.",
  bes_overall_ci: "당분기 기업경기 종합지수. 전반적 기업 심리를 요약하는 대표 지표.",
  borrowed_any_pct: "지난 1년간 차입 경험이 있는 성인 비율. 가계 신용 활용도를 반영.",
  brent_crude: "브렌트유 선물 가격. 국제 유가로 물류·제조원가와 전기요금에 파급.",
  broad_money_growth: "광의통화(M3) 증가율. 시중 유동성과 구매력 여건을 반영.",
  broadband_per100: "인구 100명당 고정 초고속인터넷 가입. 디지털 인프라·온라인 채널 저변.",
  BSP_odf_rate: "BSP 예금취급창구(ODF) 하단금리. 정책금리 회랑의 하단.",
  BSP_olf_rate: "BSP 대출취급창구(OLF) 상단금리. 정책금리 회랑의 상단.",
  bsp_policy_rate: "BSP 기준금리(RRP). 통화정책 기조와 할부·대출금리의 기준.",
  BSP_policy_rate: "필리핀 중앙은행(BSP)의 정책금리인 익일물 역환매약정(RRP) 금리(%). 통화정책 기조를 대표하는 기준금리로, 시중 대출·예금 등 각종 금리의 기준이 된다.",
  business_confidence_index: "BSP 기업기대조사(BES)의 당월 확산지수(CI). 조사 기업 중 경기를 낙관한 비율에서 비관한 비율을 뺀 값으로, 양수면 기업 심리가 순낙관임을 뜻한다.",
  business_confidence_next12m: "BSP 기업기대조사(BES) 기준 향후 12개월 경기 전망 확산지수(CI). 기업이 1년 뒤 사업 여건을 얼마나 낙관하는지를 낙관−비관 응답 차로 측정한다.",
  capacity_utilization: "제조업 평균 가동률. 생산 여력과 경기 강도를 반영.",
  cdd_monthly: "냉방도일(기준 24℃). 기온이 냉방 임계를 초과한 정도로 에어컨 수요를 선행하는 핵심 지표.",
  ces_durables_buy: "내구재를 실제 구매한 가구 비중. 내구재 소비 활동을 반영.",
  ces_durables_intent: "소비자심리조사 기준 내구재 구매의향. 가전 수요의 선행 신호.",
  construction_gfcf_growth: "건설 고정투자(GFCF) 전년비 성장률. 건설 경기와 빌트인 가전 수요를 선행.",
  construction_gva_growth: "건설업 부가가치 성장률. 건설 경기 강도를 나타냄.",
  consumer_confidence_index: "필리핀 중앙은행(BSP) 소비자기대조사(CES)의 당분기 확산지수(CI). 약 5천 가구 표본에서 낙관 응답 비율에서 비관 응답 비율을 뺀 값으로, 양수면 소비 심리가 순낙관임을 뜻한다.",
  consumer_confidence_next12m: "BSP 소비자기대조사(CES) 기준 향후 12개월 경제 전망의 확산지수(CI). 소비자가 1년 뒤 경기·가계 형편을 얼마나 낙관하는지를 낙관−비관 응답 차로 나타낸다.",
  consumer_loan_growth_yoy: "소비자대출 증가율. 가계 신용과 소비 여력을 반영.",
  CPI_aircon: "냉난방기 소비자물가지수. 에어컨 소매가 수준을 보여주는 물가 지표.",
  CPI_all_items: "전체 소비자물가지수(CPI). 생활비 수준의 종합 지표.",
  CPI_electricity: "전기료 소비자물가지수. 가계 전기요금 부담 수준.",
  CPI_food: "식료품·비주류음료 소비자물가지수. 필수 생활비 부담의 핵심.",
  cpi_forecast_adb: "ADB의 2026년 필리핀 물가 전망치. 향후 인플레이션 경로 참고.",
  CPI_household_appliances: "가전제품 소비자물가지수. 가전 소매가 수준을 직접 반영.",
  CPI_housing_utilities: "주거·수도·전기·연료 물가지수. 주거 관련 생활비 부담.",
  cpi_inflation_forecast: "BSP의 2027년 연평균 물가 전망. 중기 인플레이션 기대.",
  cpi_inflation_h1_avg: "상반기 평균 물가상승률. 연중 물가 흐름을 요약.",
  cpi_inflation_yoy: "소비자물가 상승률(전년비). 인플레이션의 핵심 지표로 구매력에 직결.",
  CPI_lpg: "LPG 소비자물가지수. 취사·연료비 부담 수준.",
  CPI_restaurants: "외식·숙박 소비자물가지수. 재량소비 부문 물가.",
  CPI_rice: "쌀 소비자물가지수. 필수 식품 물가의 핵심.",
  CPI_transport: "교통 소비자물가지수. 유가 연동 이동비용 부담.",
  credit_card_loan_growth_yoy: "신용카드 대출 증가율. 카드 기반 소비·할부 활용도.",
  credit_card_ownership: "신용카드 보유율. 할부·비대면 결제 저변.",
  credit_card_used: "신용카드 사용율. 실제 카드 결제 활용도.",
  current_account_pct_gdp: "경상수지의 GDP 대비 비율. 대외 건전성과 페소 환율 배경.",
  debit_card_ownership: "직불카드 보유율. 전자결제 접근성.",
  digital_payment_share: "소매 결제 중 디지털 결제 비중(건수). 이커머스·비대면 채널 성장.",
  domestic_credit_pct_gdp: "민간부문 신용의 GDP 대비 비율. 금융심화와 신용 여건.",
  durables_buying_intention: "향후 12개월 내구재 구매의향. 가전 수요의 선행 신호.",
  ecommerce_market_usd: "이커머스 시장 규모(달러). 온라인 판매 채널의 크기.",
  ecommerce_weekly_pct: "주간 온라인 구매 경험 비율. 이커머스 이용 빈도.",
  economic_sentiment_composite: "CES·BES 기반 자체 산출 경제심리 종합지수(실험적). 소비·기업 심리를 통합.",
  elec_access_pct: "전력 접근 가능 인구 비율. 가전 사용의 기본 인프라.",
  elec_consumption_pc: "1인당 전력소비량. 생활수준과 가전 사용 강도.",
  electrification_rate: "전기 보급률. 가전 수요의 기본 전제.",
  electrification_region: "지역별 전기 보급률. 지역 간 전력 인프라 격차.",
  emp_agri_pct: "농업 부문 고용 비중. 산업구조와 소득 기반.",
  emp_industry_pct: "산업 부문 고용 비중. 제조·건설 고용 기반.",
  emp_services_pct: "서비스 부문 고용 비중. 도시·소득 기반.",
  employed_persons: "취업자 수. 고용 규모와 소득 저변.",
  energy_households: "가정용 에너지 소비량. 가계 에너지 사용 규모.",
  energy_services: "서비스업 에너지 소비량. 상업 부문 에너지 수요.",
  energy_total: "총 에너지 소비량. 경제 활동 강도를 반영.",
  enso_oni: "엘니뇨·라니냐 지수(ONI). 이상기후로 냉방수요·작황·물가에 영향.",
  exports_gdp: "재화·서비스 수출액이 국내총생산(GDP)에서 차지하는 비율(%). 한 나라 경제가 해외 수요에 얼마나 의존하는지를 나타낸다.",
  fdi_net_inflow_usd: "외국인직접투자(FDI)의 순유입액(달러). 외국 자본이 국내 기업·사업에 투자한 금액에서 회수·철수분을 뺀 값이다.",
  fertility_rate: "여성 1명이 가임기간에 낳을 것으로 기대되는 평균 자녀 수(합계출산율). 인구의 자연 증감과 장기 인구구조를 좌우한다.",
  gdp_forecast_adb: "ADB의 2027년 GDP 성장 전망. 중기 성장 기대.",
  gdp_forecast_imf: "IMF의 2027년 GDP 성장 전망. 중기 성장 기대.",
  GDP_growth: "국내총생산(GDP)의 성장률(%). 한 나라가 생산한 재화·서비스 총량의 증감을 나타내는 경기 사이클의 핵심 지표다.",
  gdp_growth_yoy: "물가 영향을 제거한 실질 국내총생산(GDP)의 전년동기 대비 성장률(%). 한 나라가 생산한 재화·서비스의 총량이 1년 전 같은 기간보다 얼마나 늘었는지를 나타낸다.",
  gdp_per_capita_ppp: "구매력평가(PPP) 기준으로 환산한 1인당 국내총생산. 각국 물가 차이를 반영해 실질 생활수준을 국제 비교할 수 있게 한 지표다.",
  gdp_per_capita_usd: "명목 환율로 환산한 1인당 국내총생산(달러). 국민 한 사람이 생산한 부가가치의 평균 규모를 나타낸다.",
  gdp_target_govt: "정부의 2026년 GDP 성장 목표(하향조정). 정책 기대치.",
  gdp_total_ppp: "GDP 총액(PPP). 경제 규모.",
  gdp_total_usd: "명목 환율로 환산한 국내총생산 총액(달러). 한 나라 경제의 전체 규모를 나타내는 대표 지표다.",
  gfcf_growth: "총고정자본형성(설비·건설·지식재산 투자)의 증가율(%). 기업·정부가 미래 생산능력을 위해 실물자산에 투자한 규모의 변화를 나타낸다.",
  gini_index: "소득분배의 불평등도를 나타내는 지니계수(0~1). 값이 클수록 소득이 소수에 집중돼 불평등이 심함을 뜻한다.",
  gni_per_capita: "1인당 GNI(명목). 국민소득 수준.",
  govt_debt_gdp: "정부 부채 잔액이 국내총생산(GDP)에서 차지하는 비율(%). 국가 재정의 건전성과 부채 부담 정도를 가늠하는 지표다.",
  govt_exp_gdp: "정부지출의 GDP 대비 비율. 재정 부양 강도.",
  grdp_per_capita_region: "지역별 1인당 GRDP(불변). 지역 소득 격차.",
  grdp_region: "지역내총생산(GRDP, 불변). 지역 경제 규모.",
  gross_capital_formation_yoy: "총자본형성 증가율. 투자 활력.",
  gross_savings_gdp: "총저축률(%GDP). 저축·투자 여력.",
  hh_consumption_gdp: "가계소비의 GDP 비중. 내수 소비의 크기.",
  hh_consumption_growth: "가계 최종소비지출의 증가율(%). 가계가 재화·서비스 구매에 쓴 지출이 얼마나 늘었는지로 내수 소비의 활력을 보여준다.",
  hh_consumption_pc: "1인당 가계소비(불변). 개인 소비 수준.",
  household_consumption_yoy: "가계최종소비지출 증가율. 내수 강도.",
  household_income_region: "지역별 평균 가구소득(연). 지역 구매력.",
  household_size: "평균 가구원 수. 가구 구성과 가전 수요 단위.",
  households_mn: "총 가구 수. 대당 가전 수요의 기본 단위.",
  households_region: "지역별 가구 수. 지역 수요 규모.",
  imports_consumer_electronics: "소비자용 전자제품의 수입액(CIF 기준, 달러). 완제품 형태로 들여온 소비자 전자기기의 수입 규모를 집계한 값이다.",
  imports_gdp: "수입의 GDP 비중. 대외 조달 의존도.",
  imports_home_appliances: "필리핀의 가전제품 수입액(CIF 기준, 달러). 해외에서 들여온 가전제품의 수입 규모를 무역통계로 집계한 값이다.",
  imports_telecom: "통신기기 수입액(CIF). IT·통신 수요.",
  industry_gva_yoy: "산업(광공업·건설·전기 등) 부문 총부가가치의 전년 대비 증가율(%). 제조·건설 중심 실물 생산 활동의 경기 강도를 나타낸다.",
  industry_va_gdp: "산업 부가가치의 GDP 비중. 산업구조.",
  industry_va_growth: "산업 부가가치 증가율. 산업 경기 강도.",
  INF_aircon: "냉·난방기기(에어컨 등) 부문 소비자물가지수의 전년동월 대비 상승률(%). 냉난방 가전 소매가격의 변동을 측정한다.",
  INF_all_items: "전 품목을 포함한 소비자물가지수(CPI)의 전년동월 대비 상승률(%), 즉 헤드라인 인플레이션. PSA가 가계가 구매하는 고정 상품·서비스 바스켓의 평균 소매가 변동을 기준연도(2018=100) 대비로 측정한다.",
  INF_electricity: "전기요금 부문 소비자물가지수의 전년동월 대비 상승률(%). 가정용 전력 요금이 1년 전보다 얼마나 오르거나 내렸는지를 측정한다.",
  INF_food: "식료품·비주류음료 부문 소비자물가지수의 전년동월 대비 상승률(%). 가계 필수 지출의 큰 비중을 차지하는 먹거리 물가의 변동을 나타낸다.",
  INF_household_appliances: "가전제품 부문 소비자물가지수의 전년동월 대비 상승률(%). 냉장고·세탁기·TV 등 가전 소매가격이 1년 전보다 얼마나 오르거나 내렸는지를 나타낸다.",
  INF_housing_utilities: "주거·수도·전기·연료 부문 소비자물가지수의 전년동월 대비 상승률(%). 주거 관련 기초 생활비의 물가 변동을 측정한다.",
  INF_lpg: "취사·난방용 LPG(액화석유가스) 부문 소비자물가지수의 전년동월 대비 상승률(%). 가정용 가스 연료 가격의 변동을 나타낸다.",
  INF_restaurants: "외식·숙박 부문 소비자물가지수의 전년동월 대비 상승률(%). 음식점·숙박 등 서비스 소비 가격의 변동을 나타낸다.",
  INF_rice: "주식인 쌀 부문 소비자물가지수의 전년동월 대비 상승률(%). 필수 식품인 쌀 소매가격의 변동을 측정한다.",
  INF_transport: "교통 부문 소비자물가지수의 전년동월 대비 상승률(%). 연료·대중교통 등 이동 관련 비용의 물가 변동을 나타낸다.",
  infra_budget_region: "지역별 인프라 예산(DPWH). 지역 개발·건설 수요.",
  interbank_call_rate: "은행 간 초단기(익일물) 자금 거래에 적용되는 콜금리의 가중평균(%). 은행들이 하루짜리 자금을 주고받을 때의 시장 단기금리를 나타낸다.",
  internet_penetration: "인터넷 보급률. 디지털·온라인 채널 저변.",
  labor_force_participation_rate: "15세 이상 생산가능인구 중 취업자와 구직자를 합한 경제활동인구의 비율(%). 노동시장에 참여하는 인구의 크기를 나타낸다.",
  life_expectancy: "특정 연도에 태어난 사람이 향후 생존할 것으로 기대되는 평균 수명(년). 국민의 건강·의료 수준을 종합적으로 반영한다.",
  m3_growth_yoy: "광의통화(M3) 잔액의 전년동월 대비 증가율(%). 현금·요구불예금에 저축성·정기예금 등을 더한 시중 통화량의 팽창 속도를 나타낸다.",
  manuf_va_gdp: "제조업 부가가치의 GDP 비중. 제조 기반.",
  manufacturing_va_growth: "제조업 부문 부가가치의 전년 대비 증가율(%). 공장에서 생산된 재화의 부가가치가 얼마나 늘었는지로 제조 경기를 나타낸다.",
  market_cap_gdp: "상장주식 시가총액이 국내총생산(GDP)에서 차지하는 비율(%). 자본시장의 상대적 규모와 발달 정도를 나타낸다.",
  median_age: "전체 인구를 나이순으로 나열했을 때 정중앙에 위치하는 사람의 나이(중위연령). 인구의 고령화·젊음 정도를 한눈에 보여준다.",
  meralco_residential_rate: "메트로 마닐라 최대 배전사 Meralco의 가정용 전기 요금 단가(₱/kWh). 가구가 실제 부담하는 소매 전기요금 수준을 매월 나타낸다.",
  min_wage_php: "최저임금(NCR 일급). 저소득층 구매력의 기준.",
  mobile_per100: "인구 100명당 이동전화 가입. 통신 보급 수준.",
  ncr_minimum_wage: "수도권(NCR) 지역임금·생산성위원회가 고시한 비농업 부문 일 최저임금(페소/일). 마닐라 도시권 저임금 근로자의 법정 최저 하루 임금을 나타낸다.",
  npl_ratio: "은행 총여신 중 3개월 이상 연체된 부실채권(NPL)의 비율(%). 은행 자산건전성과 신용 리스크 수준을 가늠하는 지표다.",
  office_vacancy_ncr: "수도권(메트로 마닐라) 오피스 빌딩의 공실률(%). 임대되지 않고 비어 있는 사무공간의 비율로 상업용 부동산 경기를 나타낸다.",
  ofw_cash_remittance: "해외 필리핀 근로자(OFW)가 은행 등 공식 경로를 통해 본국으로 보낸 현금 송금액(달러). BSP가 월별로 집계하는 해외소득 유입의 핵심 지표다.",
  ofw_cash_remittance_growth_yoy: "OFW 현금송금 증가율. 송금 소득 흐름.",
  ofw_personal_remittance: "OFW 개인송금액(현금+현물). 해외소득 총량.",
  ofw_remittance_forecast: "BSP의 2026년 연간 송금 전망. 송금 소득 기대.",
  ofw_remittance_landbased: "육상근로자 OFW 송금액. 송금 구성의 다수.",
  ofw_remittance_seabased: "해상근로자(선원) OFW 송금액.",
  ofw_remittance_total: "OFW 해외송금 총액. 소비·구매력의 대들보.",
  oil_diesel: "경유(디젤)의 소매 판매가격(₱/리터). 화물·대중교통 등 물류·운송 연료비의 기준이 되는 유종 가격이다.",
  oil_gasoline: "휘발유의 소매 판매가격(₱/리터). 승용차 등 개인 이동 연료비를 대표하는 유종 가격이다.",
  oil_kerosene: "등유(케로신) 소매가. 취사·난방 연료비.",
  oil_ron91: "휘발유 RON91 소매가. 저옥탄 연료 가격.",
  oil_ron95: "휘발유 RON95 소매가. 고옥탄 연료 가격.",
  permits_nonresidential_floorarea: "비주거 건축허가 연면적. 상업·산업 건설 선행.",
  permits_nonresidential_value: "비주거 건축허가 금액. 상업 건설 투자.",
  permits_residential_floorarea: "정부가 승인한 주거용 건축허가의 총 연면적(㎡). 향후 1~2년 내 준공·입주로 이어질 신규 주택 공급 파이프라인을 나타낸다.",
  permits_residential_value: "주거 건축허가 금액. 주택 건설 투자.",
  permits_total_floorarea: "전체 건축허가 연면적. 건설 파이프라인.",
  permits_total_value: "전체 건축허가 금액. 건설 투자 규모.",
  php_usd_rate: "미국 달러 대비 필리핀 페소 환율(₱/US$, 종가). 1달러를 사는 데 필요한 페소 금액으로, 값이 오르면 페소 약세, 내리면 페소 강세를 뜻한다.",
  policy_rate_monthly: "BSP 정책금리(RRP) 월별. 통화정책 기조 추이.",
  pop_share_child: "유소년(0~14세) 인구 비중. 장기 수요 저변.",
  pop_share_old: "고령(65세+) 인구 비중. 고령화 진행 정도.",
  pop_share_working: "생산가능인구(15~64세) 비중. 소득·소비 핵심층.",
  pop_share_youth: "청년(20~39세) 비중. 신규 가구·가전 수요의 핵심 소비층.",
  population: "특정 시점에 한 나라에 거주하는 총인구 수. 시장의 기본 규모와 잠재 수요의 크기를 나타낸다.",
  population_region: "지역별 인구. 지역 수요 규모.",
  poverty_rate: "소득이 최저생계선(빈곤선)에 못 미치는 인구의 비율(%). 국민 중 빈곤 상태에 있는 사람의 규모를 나타낸다.",
  poverty_rate_region: "지역별 빈곤율. 지역 구매력 격차.",
  PPI_domestic_appliances: "국내 가전제품 제조업의 생산자물가지수(PPI) 전년 대비 변동률(%). 공장 출고 단계에서 제조업체가 받는 가전 판매가격의 변동을 측정한다.",
  PPI_electrical: "전기장비 생산자물가(전년비). 전기제품 원가.",
  PPI_electronics: "전자·컴퓨터 생산자물가(전년비). 전자제품 원가.",
  PPI_manufacturing: "제조업 생산자물가(전년비). 전반적 생산원가.",
  psei_index: "필리핀 증권거래소 대표 주가지수(PSEi, 월말 종가). 시가총액·유동성 상위 30개 대형 상장기업으로 구성된 벤치마크 지수다.",
  remittances_usd: "해외송금 수취액(달러). 가계 외화소득.",
  reserves_usd: "외환보유액(달러). 대외 방어력과 환율 안정성.",
  residential_property_price_index: "주거용 부동산가격지수(명목, 2010=100). 주택 자산가치.",
  residential_property_price_real_yoy: "주거용 부동산가격 실질 상승률. 물가 조정 후 주택가격.",
  residential_property_price_yoy: "주거용 부동산가격 명목 상승률. 주택 경기 방향.",
  retail_gva_growth: "소매업 부가가치 성장률. 소매 경기.",
  retail_sales_bn: "소매판매액. 내수 소비 규모.",
  retail_sales_growth: "소매판매 증가율. 소비 활력.",
  rppi_index: "필리핀 중앙은행(BSP)이 은행 주택담보대출 실거래 자료를 헤도닉 회귀로 산출하는 전국 주택가격지수(2019=100, 분기). 단독·타운하우스·콘도 등 주택 유형과 수도권(NCR)·지방을 구분해 주거용 부동산 가격 변동을 측정한다.",
  rppi_index_condo: "RPPI 하위지수 중 콘도미니엄(공동주택) 유형의 가격지수(2019=100, 분기). BSP가 은행 대출자료를 바탕으로 도심 공동주택의 실거래가 수준 변화를 추정한다.",
  rppi_index_house: "RPPI 하위지수 중 단독주택 유형의 가격지수(2019=100, 분기). 단독주택 실거래가 수준의 분기별 변화를 헤도닉 방식으로 측정한다.",
  rppi_yoy: "주택가격지수(RPPI)의 전년동기 대비 변동률(%). 전국 주택 실거래가가 1년 전 같은 분기보다 얼마나 오르거나 내렸는지를 나타낸다.",
  saved_at_fi_pct: "금융기관 저축 보유 성인 비율. 저축 기반.",
  secondary_enroll: "중등학교 취학률(총). 인적자본·중산층 형성.",
  secure_internet_servers: "백만명당 보안 인터넷서버. 디지털 인프라 성숙도.",
  services_gva_yoy: "서비스 부문 총부가가치 증가율. 서비스 경기.",
  services_pct_gdp: "서비스업 GDP 비중. 산업구조.",
  services_va_gdp: "서비스 부가가치의 GDP 비중.",
  services_va_growth: "서비스업 부가가치 증가율. 서비스 경기 강도.",
  tax_revenue_gdp: "조세수입의 GDP 비중. 재정 기반.",
  temp_monthly: "메트로마닐라 월평균 기온. 냉방수요와 직접 연동.",
  tourism_arrivals: "국제 관광객 입국자 수. 서비스 경기·소비 활력.",
  trade_balance_gdp: "무역수지의 GDP 비중. 대외 균형.",
  underemployment_rate: "불완전취업률. 고용의 질과 잠재 소득 여력.",
  unemployment_rate: "경제활동인구(15세 이상 취업자+구직자) 가운데 일자리 없이 적극적으로 구직 중인 사람의 비율(%). PSA 노동력조사(LFS)로 매월 집계한다.",
  urban_pop_pct: "도시인구 비중. 도시화와 가전 수요 밀도.",
  urban_population_pct: "도시화율. 도시 거주 인구 비율.",
  wholesale_gva_growth: "도매업 부가가치 성장률. 유통 경기.",
  wholesale_retail_gva_growth: "도소매 전체 부가가치 성장률. 유통 경기 종합.",
  wholesale_retail_trade_yoy: "도소매 부가가치 성장률. 유통 부문 경기.",
}
