/** 전체 지표 리스트(AllIndicatorsView)용 영문 라벨 맵.
 *  v_data_provenance.label 은 한글 원문만 제공(EN 컬럼 없음) → indicator 키별 영문 라벨을 코드로 매핑.
 *  약어(CPI/GDP/PPI/RPPI/OFW/BSP/M3/FDI/GVA/GRDP/GNI/CDD/NPL 등)는 그대로 사용.
 *  표시(pickL/pick)에서만 참조 — 매칭·정렬·로직 키로 사용 금지. */
export const INDICATOR_EN: Record<string, string> = {
  policy_rate_monthly: "BSP Policy Rate (RRP), monthly",
  CPI_rice: "CPI Rice",
  bes_overall_ci: "Business Expectations Composite Index (current quarter)",
  electrification_rate: "Electrification rate",
  cpi_inflation_forecast: "BSP Avg. Inflation Forecast (2027)",
  meralco_residential_rate: "Meralco Residential Electricity Rate",
  imports_consumer_electronics: "Consumer Electronics Imports (CIF)",
  CPI_transport: "CPI Transport",
  CPI_housing_utilities: "CPI Housing, Water, Electricity & Fuels",
  fdi_net_inflow_usd: "FDI Net Inflow",
  CPI_household_appliances: "CPI Household Appliances",
  psei_index: "PSEi Index (month-end)",
  residential_property_price_real_yoy: "Residential Property Price Growth (real)",
  rppi_index_house: "RPPI (houses)",
  govt_debt_gdp: "Government Debt (% GDP)",
  cpi_inflation_yoy: "CPI Inflation rate",
  INF_electricity: "Electricity Inflation (YoY)",
  households_mn: "Number of Households",
  imports_home_appliances: "Home Appliance Imports (CIF)",
  interbank_call_rate: "Interbank Call Rate (weighted avg.)",
  gdp_growth_yoy: "GDP Growth (YoY)",
  energy_households: "Household Energy Consumption",
  grdp_region: "Gross Regional Domestic Product (GRDP, constant 2018)",
  gross_savings_gdp: "Gross Savings Rate (% GDP)",
  PPI_electrical: "PPI Electrical Equipment (YoY)",
  ncr_minimum_wage: "NCR Daily Minimum Wage (non-agriculture)",
  gdp_forecast_adb: "ADB GDP Growth Forecast (2027)",
  household_consumption_yoy: "Household Final Consumption Growth",
  PPI_domestic_appliances: "PPI Domestic Appliance Manufacturing (YoY)",
  tax_revenue_gdp: "Tax Revenue (% GDP)",
  credit_card_loan_growth_yoy: "Credit Card Loan Growth",
  wholesale_retail_gva_growth: "Wholesale & Retail GVA Growth (YoY)",
  appliance_market_usd: "Philippine Appliance Market Size",
  php_usd_rate: "PHP/USD Exchange Rate (close)",
  hh_consumption_gdp: "Household Consumption (% GDP)",
  services_gva_yoy: "Services Sector GVA Growth",
  INF_all_items: "All-Items Inflation (YoY)",
  tourism_arrivals: "International Tourist Arrivals",
  bes_con_interest: "High Interest Rates (constraint)",
  labor_force_participation_rate: "Labor Force Participation Rate",
  saved_at_fi_pct: "Saved at a Financial Institution (%)",
  fertility_rate: "Total Fertility Rate",
  office_vacancy_ncr: "Metro Manila Office Vacancy Rate",
  residential_property_price_yoy: "Residential Property Price Growth (nominal)",
  oil_ron95: "Gasoline RON95",
  durables_buying_intention: "Durable-Goods Buying Intention (next 12M)",
  gni_per_capita: "GNI per Capita (nominal)",
  secondary_enroll: "Secondary School Enrollment (gross)",
  ecommerce_weekly_pct: "Weekly Online Purchase Rate",
  broadband_per100: "Fixed Broadband (per 100 people)",
  industry_va_growth: "Industry Value-Added Growth",
  emp_agri_pct: "Agriculture Employment Share",
  construction_gva_growth: "Construction GVA Growth (YoY)",
  gdp_forecast_imf: "IMF GDP Growth Forecast (2027)",
  broad_money_growth: "Broad Money (M3) Growth",
  capacity_utilization: "Capacity Utilization (manufacturing)",
  gdp_total_ppp: "GDP (PPP)",
  oil_diesel: "Diesel Retail Price",
  oil_gasoline: "Gasoline Retail Price",
  permits_nonresidential_value: "Building Permits, Non-Residential (value)",
  ofw_remittance_forecast: "BSP Annual Remittance Forecast (2026)",
  gfcf_growth: "Gross Fixed Capital Formation Growth",
  median_age: "Median Age",
  gdp_per_capita_usd: "GDP per Capita (nominal)",
  CPI_lpg: "CPI LPG",
  bes_expansion_plans: "Capacity Expansion Plans (%)",
  permits_residential_floorarea: "Building Permits, Residential (floor area)",
  PPI_electronics: "PPI Electronics & Computers (YoY)",
  manufacturing_va_growth: "Manufacturing Value-Added Growth",
  underemployment_rate: "Underemployment Rate",
  CPI_electricity: "CPI Electricity",
  pop_share_working: "Working-Age (15-64) Share",
  bes_con_demand: "Insufficient Demand (constraint)",
  urban_pop_pct: "Urban Population Share",
  bes_ci_retail: "Sector Confidence - Wholesale & Retail",
  internet_penetration: "Internet Penetration",
  emp_industry_pct: "Industry Employment Share",
  emp_services_pct: "Services Employment Share",
  min_wage_php: "Minimum Wage (NCR daily)",
  rppi_index: "RPPI",
  credit_card_used: "Credit Card Usage Rate",
  hh_consumption_growth: "Household Final Consumption Growth",
  ces_durables_buy: "Households Buying Durables (share)",
  pop_share_old: "Elderly (65+) Share",
  reserves_usd: "Gross International Reserves (USD)",
  INF_transport: "Transport Inflation (YoY)",
  ces_durables_intent: "Durable-Goods Buying Intention (CES)",
  cdd_monthly: "Cooling Degree Days (CDD, 24℃)",
  permits_total_floorarea: "Building Permits, Total (floor area)",
  permits_total_value: "Building Permits, Total (value)",
  grdp_per_capita_region: "GRDP per Capita (constant 2018)",
  CPI_restaurants: "CPI Restaurants & Accommodation",
  poverty_rate: "Poverty Incidence",
  gdp_target_govt: "Government GDP Growth Target (2026, revised down)",
  domestic_credit_pct_gdp: "Domestic Credit to Private Sector (% GDP)",
  economic_sentiment_composite: "Economic Sentiment Index (in-house, experimental)",
  infra_budget_region: "Regional Infrastructure Budget",
  wholesale_gva_growth: "Wholesale Trade GVA Growth (YoY)",
  ofw_remittance_landbased: "OFW Remittances (land-based)",
  services_va_gdp: "Services Value-Added (% GDP)",
  pop_share_child: "Children (0-14) Share",
  bes_con_financial: "Financial Problems (constraint)",
  market_cap_gdp: "Stock Market Cap (% GDP)",
  population_region: "Regional Population",
  remittances_usd: "Overseas Remittance Receipts",
  permits_nonresidential_floorarea: "Building Permits, Non-Residential (floor area)",
  exports_gdp: "Exports (% GDP)",
  appliance_market_cagr: "Appliance Market CAGR (25-30)",
  ofw_remittance_seabased: "OFW Remittances (sea-based)",
  business_confidence_next12m: "Business Confidence Index (BCI, next 12M)",
  electrification_region: "Electrification rate (regional)",
  appl_own_ref: "Refrigerator Ownership",
  retail_sales_bn: "Retail Sales",
  borrowed_any_pct: "Borrowed Any Money (%)",
  debit_card_ownership: "Debit Card Ownership",
  INF_restaurants: "Restaurants & Accommodation Inflation (YoY)",
  ecommerce_market_usd: "E-commerce Market Size",
  employed_persons: "Employed Persons",
  gross_capital_formation_yoy: "Gross Capital Formation Growth",
  CPI_all_items: "CPI (all items)",
  bes_ci_services: "Sector Confidence - Services",
  CPI_food: "CPI Food & Non-Alcoholic Beverages",
  INF_aircon: "Air-Conditioner Inflation (YoY)",
  urban_population_pct: "Urbanization Rate",
  appl_own_tv_region: "TV Ownership (regional)",
  digital_payment_share: "Digital Payment Share (retail, volume)",
  residential_property_price_index: "Residential Property Price Index (nominal, 2010=100)",
  oil_ron91: "Gasoline RON91",
  pop_share_youth: "Youth (20-39) Share",
  npl_ratio: "Non-Performing Loan (NPL) Ratio",
  PPI_manufacturing: "PPI Manufacturing (YoY)",
  construction_gfcf_growth: "Construction Investment (GFCF) Growth (YoY)",
  bes_ci_next_q: "Business Outlook (next quarter)",
  ofw_personal_remittance: "OFW Personal Remittances",
  ofw_cash_remittance: "OFW Cash Remittances",
  cpi_forecast_adb: "ADB Inflation Forecast (2026)",
  brent_crude: "Brent Crude Futures",
  m3_growth_yoy: "Money Supply (M3) Growth",
  business_confidence_index: "Business Confidence Index (BCI, current)",
  appl_own_mobile: "Mobile Phone Ownership",
  life_expectancy: "Life Expectancy",
  trade_balance_gdp: "Trade Balance (% GDP)",
  retail_gva_growth: "Retail Trade GVA Growth (YoY)",
  permits_residential_value: "Building Permits, Residential (value)",
  consumer_confidence_next12m: "Consumer Confidence Index (CCI, next 12M)",
  gini_index: "Gini Index (income inequality)",
  current_account_pct_gdp: "Current Account (% GDP)",
  BSP_policy_rate: "BSP Policy Rate (RRP)",
  poverty_rate_region: "Regional Poverty Incidence",
  elec_access_pct: "Electricity Access Rate",
  appl_own_cool: "Air-Cooling / Fan Ownership",
  INF_lpg: "LPG Inflation (YoY)",
  bes_employment_outlook: "Employment Outlook Index (next quarter)",
  enso_oni: "ENSO Oceanic Niño Index (ONI)",
  cpi_inflation_h1_avg: "H1 Average Inflation",
  BSP_olf_rate: "BSP Overnight Lending Facility Rate (OLF)",
  credit_card_ownership: "Credit Card Ownership",
  consumer_loan_growth_yoy: "Consumer Loan Growth",
  bes_con_competition: "Intensifying Competition (constraint)",
  INF_housing_utilities: "Housing, Water, Electricity & Fuels Inflation (YoY)",
  oil_kerosene: "Kerosene Retail Price",
  mobile_per100: "Mobile Subscriptions (per 100 people)",
  manuf_va_gdp: "Manufacturing Value-Added (% GDP)",
  households_region: "Regional Households",
  population: "Population",
  services_va_growth: "Services Value-Added Growth",
  bes_ci_next12m: "Business Outlook (next 12M)",
  household_income_region: "Regional Avg. Household Income (annual)",
  bes_credit_access: "Credit Access Index",
  ofw_remittance_total: "OFW Overseas Remittances (total)",
  CPI_aircon: "CPI Air-Conditioner",
  account_ownership: "Account Ownership (15+)",
  energy_total: "Total Energy Consumption",
  BSP_odf_rate: "BSP Overnight Deposit Facility Rate (ODF)",
  industry_va_gdp: "Industry Value-Added (% GDP)",
  retail_sales_growth: "Retail Sales Growth",
  services_pct_gdp: "Services Share of GDP",
  bank_loan_growth_yoy: "Bank Total Loan Growth (U/KB)",
  bes_financial_condition: "Financial Condition Index",
  gdp_total_usd: "GDP (nominal)",
  temp_monthly: "Monthly Avg. Temperature (Metro Manila)",
  hh_consumption_pc: "Household Consumption per Capita (constant 2015 $)",
  bsp_policy_rate: "BSP Policy Rate (RRP)",
  ofw_cash_remittance_growth_yoy: "OFW Cash Remittance Growth",
  imports_gdp: "Imports (% GDP)",
  unemployment_rate: "Unemployment rate",
  consumer_confidence_index: "Consumer Confidence Index (CCI, current quarter)",
  GDP_growth: "GDP Growth",
  industry_gva_yoy: "Industry Sector GVA Growth",
  elec_consumption_pc: "Electricity Consumption per Capita",
  INF_rice: "Rice Inflation (YoY)",
  bes_capacity_util: "Average Capacity Utilization (BES)",
  rppi_yoy: "RPPI Growth (YoY)",
  imports_telecom: "Telecom Equipment Imports (CIF)",
  govt_exp_gdp: "Government Expenditure (% GDP)",
  household_size: "Average Household Size",
  appl_own_tv: "TV Ownership",
  appl_own_ref_region: "Refrigerator Ownership (regional)",
  secure_internet_servers: "Secure Internet Servers (per million people)",
  bes_ci_manufacturing: "Sector Confidence - Manufacturing",
  INF_household_appliances: "Household Appliance Inflation (YoY)",
  wholesale_retail_trade_yoy: "Wholesale & Retail Trade GVA Growth",
  INF_food: "Food & Non-Alcoholic Beverages Inflation (YoY)",
  appl_own_wash: "Washing Machine Ownership",
  energy_services: "Services Sector Energy Consumption",
  gdp_per_capita_ppp: "GDP per Capita (PPP)",
  rppi_index_condo: "RPPI (condominiums)",
}
